// Package test contains E2E tests for roji.
//
// These tests start a real roji server with TLS and make actual HTTP requests.
// They require Docker to be running.
//
// Run with: go test -v -tags=e2e -timeout=5m ./test/...
//
//go:build e2e

package test

import (
	"bufio"
	"context"
	"crypto/tls"
	"crypto/x509"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/kan/roji/certgen"
	"github.com/kan/roji/docker"
	"github.com/kan/roji/proxy"
)

func startContainers() error {
	cmd := exec.Command("docker", "compose", "-f", "docker-compose.yml", "up", "-d")
	cmd.Dir = "."
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func stopContainers() error {
	cmd := exec.Command("docker", "compose", "-f", "docker-compose.yml", "down", "-v")
	cmd.Dir = "."
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

const (
	e2eNetwork      = "roji-test"
	e2eBaseDomain   = "test.localhost"
	e2eDashboardHost = "roji.test.localhost"
	e2eHTTPPort     = 18080
	e2eHTTPSPort    = 18443
)

var (
	testServer   *e2eServer
	testCertsDir string
)

type e2eServer struct {
	handler      *proxy.Handler
	router       *proxy.Router
	dockerClient *docker.Client
	httpServer   *http.Server
	httpsServer  *http.Server
	tlsConfig    *tls.Config
	clientConfig *tls.Config
}

// TestMain handles setup and teardown for E2E tests
func TestMain(m *testing.M) {
	// Start test containers
	if err := startContainers(); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to start test containers: %v\n", err)
		os.Exit(1)
	}

	// Wait for containers to be ready
	time.Sleep(3 * time.Second)

	// Setup E2E server
	var err error
	testServer, err = setupE2EServer()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to setup E2E server: %v\n", err)
		stopContainers()
		os.Exit(1)
	}

	// Run tests
	code := m.Run()

	// Cleanup
	testServer.stop()
	stopContainers()

	// Remove temp certs dir
	if testCertsDir != "" {
		os.RemoveAll(testCertsDir)
	}

	os.Exit(code)
}

func setupE2EServer() (*e2eServer, error) {
	// Create temp directory for certificates
	var err error
	testCertsDir, err = os.MkdirTemp("", "roji-e2e-certs-*")
	if err != nil {
		return nil, fmt.Errorf("failed to create temp certs dir: %w", err)
	}

	// Generate certificates
	gen := certgen.NewGenerator(testCertsDir, e2eBaseDomain)
	if err := gen.EnsureCerts(); err != nil {
		return nil, fmt.Errorf("failed to generate certificates: %w", err)
	}

	// Load server TLS config
	serverCert, err := tls.LoadX509KeyPair(
		filepath.Join(testCertsDir, "cert.pem"),
		filepath.Join(testCertsDir, "key.pem"),
	)
	if err != nil {
		return nil, fmt.Errorf("failed to load server cert: %w", err)
	}

	serverTLSConfig := &tls.Config{
		Certificates: []tls.Certificate{serverCert},
		MinVersion:   tls.VersionTLS12,
	}

	// Load CA for client verification
	caCert, err := os.ReadFile(filepath.Join(testCertsDir, "ca.pem"))
	if err != nil {
		return nil, fmt.Errorf("failed to read CA cert: %w", err)
	}

	caPool := x509.NewCertPool()
	if !caPool.AppendCertsFromPEM(caCert) {
		return nil, fmt.Errorf("failed to parse CA cert")
	}

	clientTLSConfig := &tls.Config{
		RootCAs:    caPool,
		MinVersion: tls.VersionTLS12,
	}

	// Setup Docker client and router
	dockerClient, err := docker.NewClient([]string{e2eNetwork}, e2eBaseDomain)
	if err != nil {
		return nil, fmt.Errorf("failed to create docker client: %w", err)
	}

	router := proxy.NewRouter()

	// Discover backends
	ctx := context.Background()
	backends, err := dockerClient.DiscoverBackends(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to discover backends: %w", err)
	}

	for _, backend := range backends {
		router.AddBackend(backend)
	}

	statusConfig := &proxy.StatusConfig{
		Version:       "e2e-test",
		StartTime:     time.Now(),
		CertsDir:      testCertsDir,
		AutoGenerated: true,
		Networks:      []string{e2eNetwork},
		BaseDomain:    e2eBaseDomain,
		HTTPPort:      e2eHTTPPort,
		HTTPSPort:     e2eHTTPSPort,
	}

	handler := proxy.NewHandler(router, dockerClient, e2eDashboardHost, e2eBaseDomain, statusConfig, nil)

	// Create HTTP server (for redirect)
	httpServer := &http.Server{
		Addr:    fmt.Sprintf(":%d", e2eHTTPPort),
		Handler: &proxy.RedirectHandler{HTTPSPort: e2eHTTPSPort},
	}

	// Create HTTPS server
	httpsServer := &http.Server{
		Addr:      fmt.Sprintf(":%d", e2eHTTPSPort),
		Handler:   handler,
		TLSConfig: serverTLSConfig,
	}

	server := &e2eServer{
		handler:      handler,
		router:       router,
		dockerClient: dockerClient,
		httpServer:   httpServer,
		httpsServer:  httpsServer,
		tlsConfig:    serverTLSConfig,
		clientConfig: clientTLSConfig,
	}

	// Start servers
	go func() {
		if err := httpServer.ListenAndServe(); err != http.ErrServerClosed {
			fmt.Fprintf(os.Stderr, "HTTP server error: %v\n", err)
		}
	}()

	go func() {
		if err := httpsServer.ListenAndServeTLS("", ""); err != http.ErrServerClosed {
			fmt.Fprintf(os.Stderr, "HTTPS server error: %v\n", err)
		}
	}()

	// Wait for servers to be ready
	time.Sleep(500 * time.Millisecond)

	return server, nil
}

func (s *e2eServer) stop() {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	s.httpServer.Shutdown(ctx)
	s.httpsServer.Shutdown(ctx)
	s.dockerClient.Close()
}

func (s *e2eServer) httpClient() *http.Client {
	return &http.Client{
		Transport: &http.Transport{
			TLSClientConfig: s.clientConfig,
			// Disable connection reuse for cleaner tests
			DisableKeepAlives: true,
		},
		Timeout: 10 * time.Second,
		// Don't follow redirects automatically
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			return http.ErrUseLastResponse
		},
	}
}

// resolveHost creates a dialer that resolves test hostnames to localhost
func resolveHost(port int) func(ctx context.Context, network, addr string) (net.Conn, error) {
	return func(ctx context.Context, network, addr string) (net.Conn, error) {
		// Replace any *.test.localhost with localhost:port
		if strings.HasSuffix(addr, ".test.localhost:"+fmt.Sprint(port)) ||
			strings.HasSuffix(addr, ".test.localhost") {
			addr = fmt.Sprintf("127.0.0.1:%d", port)
		}
		return (&net.Dialer{}).DialContext(ctx, network, addr)
	}
}

func (s *e2eServer) httpClientWithResolver() *http.Client {
	transport := &http.Transport{
		TLSClientConfig: s.clientConfig,
		DialContext:     resolveHost(e2eHTTPSPort),
	}
	return &http.Client{
		Transport: transport,
		Timeout:   10 * time.Second,
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			return http.ErrUseLastResponse
		},
	}
}

// E2E Tests

// TestE2E_TLSCertificateVerification verifies TLS works with generated certificates
func TestE2E_TLSCertificateVerification(t *testing.T) {
	client := testServer.httpClientWithResolver()

	// Test HTTPS connection with CA verification
	resp, err := client.Get(fmt.Sprintf("https://%s:%d/", e2eDashboardHost, e2eHTTPSPort))
	if err != nil {
		t.Fatalf("Failed to connect with TLS: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		t.Errorf("Status = %d, want %d", resp.StatusCode, http.StatusOK)
	}

	// Verify TLS connection details
	if resp.TLS == nil {
		t.Fatal("Expected TLS connection")
	}

	if resp.TLS.Version < tls.VersionTLS12 {
		t.Errorf("TLS version = %d, want >= TLS 1.2", resp.TLS.Version)
	}

	// Verify certificate chain
	if len(resp.TLS.PeerCertificates) == 0 {
		t.Error("No peer certificates received")
	}
}

// TestE2E_TLSCertificateRejection verifies connection fails without CA
func TestE2E_TLSCertificateRejection(t *testing.T) {
	// Create client without CA (should fail)
	client := &http.Client{
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{
				// No RootCAs - will use system pool which doesn't have our CA
			},
			DialContext: resolveHost(e2eHTTPSPort),
		},
		Timeout: 5 * time.Second,
	}

	_, err := client.Get(fmt.Sprintf("https://%s:%d/", e2eDashboardHost, e2eHTTPSPort))
	if err == nil {
		t.Error("Expected TLS verification error, but connection succeeded")
	}

	// Error should be about certificate verification
	if !strings.Contains(err.Error(), "certificate") {
		t.Logf("Got error: %v", err)
		// This is still acceptable - connection should fail
	}
}

// TestE2E_HTTPToHTTPSRedirect verifies HTTP redirects to HTTPS
func TestE2E_HTTPToHTTPSRedirect(t *testing.T) {
	client := &http.Client{
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			return http.ErrUseLastResponse
		},
		Timeout: 5 * time.Second,
	}

	resp, err := client.Get(fmt.Sprintf("http://127.0.0.1:%d/", e2eHTTPPort))
	if err != nil {
		t.Fatalf("Failed to connect: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusMovedPermanently {
		t.Errorf("Status = %d, want %d", resp.StatusCode, http.StatusMovedPermanently)
	}

	location := resp.Header.Get("Location")
	if !strings.HasPrefix(location, "https://") {
		t.Errorf("Location = %q, should start with https://", location)
	}

	if !strings.Contains(location, fmt.Sprintf(":%d", e2eHTTPSPort)) {
		t.Errorf("Location = %q, should contain port %d", location, e2eHTTPSPort)
	}
}

// TestE2E_DashboardAccess verifies dashboard is accessible via HTTPS
func TestE2E_DashboardAccess(t *testing.T) {
	client := testServer.httpClientWithResolver()

	resp, err := client.Get(fmt.Sprintf("https://%s:%d/", e2eDashboardHost, e2eHTTPSPort))
	if err != nil {
		t.Fatalf("Failed to access dashboard: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		t.Errorf("Status = %d, want %d", resp.StatusCode, http.StatusOK)
	}

	body, _ := io.ReadAll(resp.Body)
	bodyStr := string(body)

	// Check for dashboard content
	if !strings.Contains(bodyStr, "roji") {
		t.Error("Dashboard should contain 'roji'")
	}
	if !strings.Contains(bodyStr, "Dashboard") {
		t.Error("Dashboard should contain 'Dashboard'")
	}
	if !strings.Contains(bodyStr, "PetiteVue") || !strings.Contains(bodyStr, "petite-vue") {
		t.Error("Dashboard should include Petite Vue")
	}
}

// TestE2E_APIEndpoints verifies API endpoints work over HTTPS
func TestE2E_APIEndpoints(t *testing.T) {
	client := testServer.httpClientWithResolver()

	endpoints := []struct {
		path       string
		wantStatus int
		checkBody  func(t *testing.T, body []byte)
	}{
		{
			path:       "/_api/health",
			wantStatus: http.StatusOK,
			checkBody: func(t *testing.T, body []byte) {
				var health map[string]interface{}
				if err := json.Unmarshal(body, &health); err != nil {
					t.Errorf("Failed to parse health response: %v", err)
					return
				}
				if health["status"] != "healthy" {
					t.Errorf("Health status = %v, want 'healthy'", health["status"])
				}
			},
		},
		{
			path:       "/_api/routes",
			wantStatus: http.StatusOK,
			checkBody: func(t *testing.T, body []byte) {
				var routes []map[string]interface{}
				if err := json.Unmarshal(body, &routes); err != nil {
					t.Errorf("Failed to parse routes response: %v", err)
					return
				}
				if len(routes) < 1 {
					t.Error("Expected at least 1 route")
				}
			},
		},
		{
			path:       "/_api/status",
			wantStatus: http.StatusOK,
			checkBody: func(t *testing.T, body []byte) {
				var status map[string]interface{}
				if err := json.Unmarshal(body, &status); err != nil {
					t.Errorf("Failed to parse status response: %v", err)
					return
				}
				if status["health"] != "healthy" && status["health"] != "degraded" {
					t.Errorf("Health = %v, want 'healthy' or 'degraded'", status["health"])
				}
			},
		},
		{
			path:       "/_api/logs",
			wantStatus: http.StatusOK,
			checkBody: func(t *testing.T, body []byte) {
				var logs []map[string]interface{}
				if err := json.Unmarshal(body, &logs); err != nil {
					t.Errorf("Failed to parse logs response: %v", err)
				}
				// Logs may be empty, that's OK
			},
		},
	}

	for _, tt := range endpoints {
		t.Run(tt.path, func(t *testing.T) {
			resp, err := client.Get(fmt.Sprintf("https://%s:%d%s", e2eDashboardHost, e2eHTTPSPort, tt.path))
			if err != nil {
				t.Fatalf("Failed to access %s: %v", tt.path, err)
			}
			defer resp.Body.Close()

			if resp.StatusCode != tt.wantStatus {
				t.Errorf("Status = %d, want %d", resp.StatusCode, tt.wantStatus)
			}

			body, _ := io.ReadAll(resp.Body)
			if tt.checkBody != nil {
				tt.checkBody(t, body)
			}
		})
	}
}

// TestE2E_SSEConnection verifies SSE connection works
func TestE2E_SSEConnection(t *testing.T) {
	client := testServer.httpClientWithResolver()

	req, err := http.NewRequest("GET", fmt.Sprintf("https://%s:%d/_api/events", e2eDashboardHost, e2eHTTPSPort), nil)
	if err != nil {
		t.Fatalf("Failed to create request: %v", err)
	}
	req.Header.Set("Accept", "text/event-stream")

	resp, err := client.Do(req)
	if err != nil {
		t.Fatalf("Failed to connect to SSE: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		t.Errorf("Status = %d, want %d", resp.StatusCode, http.StatusOK)
	}

	// Check SSE headers
	contentType := resp.Header.Get("Content-Type")
	if contentType != "text/event-stream" {
		t.Errorf("Content-Type = %q, want 'text/event-stream'", contentType)
	}

	// Read initial routes event
	scanner := bufio.NewScanner(resp.Body)
	var receivedEvent bool
	timeout := time.After(3 * time.Second)
	done := make(chan bool)

	go func() {
		for scanner.Scan() {
			line := scanner.Text()
			if strings.HasPrefix(line, "event: routes") {
				receivedEvent = true
				done <- true
				return
			}
		}
		done <- false
	}()

	select {
	case success := <-done:
		if !success && !receivedEvent {
			t.Error("Did not receive initial routes event")
		}
	case <-timeout:
		if !receivedEvent {
			t.Error("Timeout waiting for SSE event")
		}
	}
}

// TestE2E_SSERealtimeUpdates verifies SSE receives real-time route updates
func TestE2E_SSERealtimeUpdates(t *testing.T) {
	client := testServer.httpClientWithResolver()

	// Connect to SSE
	req, err := http.NewRequest("GET", fmt.Sprintf("https://%s:%d/_api/events", e2eDashboardHost, e2eHTTPSPort), nil)
	if err != nil {
		t.Fatalf("Failed to create request: %v", err)
	}

	resp, err := client.Do(req)
	if err != nil {
		t.Fatalf("Failed to connect to SSE: %v", err)
	}
	defer resp.Body.Close()

	// Read events in background
	var events []string
	var mu sync.Mutex
	go func() {
		scanner := bufio.NewScanner(resp.Body)
		for scanner.Scan() {
			line := scanner.Text()
			if strings.HasPrefix(line, "event:") || strings.HasPrefix(line, "data:") {
				mu.Lock()
				events = append(events, line)
				mu.Unlock()
			}
		}
	}()

	// Wait for initial event
	time.Sleep(500 * time.Millisecond)

	mu.Lock()
	initialCount := len(events)
	mu.Unlock()

	if initialCount < 2 { // event: routes + data: [...]
		t.Errorf("Expected at least 2 lines (event + data), got %d", initialCount)
	}

	// Verify the data is valid JSON
	mu.Lock()
	for _, line := range events {
		if strings.HasPrefix(line, "data:") {
			data := strings.TrimPrefix(line, "data: ")
			var routes []interface{}
			if err := json.Unmarshal([]byte(data), &routes); err != nil {
				t.Errorf("Failed to parse SSE data as JSON: %v", err)
			}
		}
	}
	mu.Unlock()
}

// TestE2E_ProxyToBackend verifies proxying to actual backend containers
func TestE2E_ProxyToBackend(t *testing.T) {
	client := testServer.httpClientWithResolver()

	// Get routes to find a valid backend
	resp, err := client.Get(fmt.Sprintf("https://%s:%d/_api/routes", e2eDashboardHost, e2eHTTPSPort))
	if err != nil {
		t.Fatalf("Failed to get routes: %v", err)
	}
	defer resp.Body.Close()

	var routes []struct {
		Hostname string `json:"hostname"`
		Target   string `json:"target"`
		Warning  string `json:"warning"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&routes); err != nil {
		t.Fatalf("Failed to decode routes: %v", err)
	}

	// Find a route without warning (has valid port)
	var testHost string
	for _, r := range routes {
		if r.Warning == "" && r.Target != "" {
			testHost = r.Hostname
			break
		}
	}

	if testHost == "" {
		t.Skip("No valid backend route found for proxy test")
	}

	// Test proxy to backend
	resp, err = client.Get(fmt.Sprintf("https://%s:%d/", testHost, e2eHTTPSPort))
	if err != nil {
		t.Fatalf("Failed to proxy to %s: %v", testHost, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		t.Errorf("Proxy status = %d, want %d", resp.StatusCode, http.StatusOK)
	}

	body, _ := io.ReadAll(resp.Body)
	// Should get nginx response
	if !strings.Contains(string(body), "nginx") {
		t.Errorf("Expected nginx response, got: %s", string(body)[:min(len(body), 200)])
	}
}

// TestE2E_MockRoutes verifies mock routes work over HTTPS
func TestE2E_MockRoutes(t *testing.T) {
	client := testServer.httpClientWithResolver()

	tests := []struct {
		method     string
		path       string
		wantStatus int
		wantBody   string
	}{
		{"GET", "/api/users", 200, `[{"id":1,"name":"Test User"}]`},
		{"GET", "/api/health", 200, `{"status":"ok"}`},
		{"POST", "/api/users", 201, `{"created":true}`},
	}

	for _, tt := range tests {
		t.Run(tt.method+" "+tt.path, func(t *testing.T) {
			req, err := http.NewRequest(tt.method, fmt.Sprintf("https://mock.test.localhost:%d%s", e2eHTTPSPort, tt.path), nil)
			if err != nil {
				t.Fatalf("Failed to create request: %v", err)
			}

			resp, err := client.Do(req)
			if err != nil {
				t.Fatalf("Failed to make request: %v", err)
			}
			defer resp.Body.Close()

			if resp.StatusCode != tt.wantStatus {
				t.Errorf("Status = %d, want %d", resp.StatusCode, tt.wantStatus)
			}

			body, _ := io.ReadAll(resp.Body)
			if strings.TrimSpace(string(body)) != tt.wantBody {
				t.Errorf("Body = %q, want %q", string(body), tt.wantBody)
			}

			// Check mock header
			if resp.Header.Get("X-Roji-Mock") != "true" {
				t.Error("Expected X-Roji-Mock header")
			}
		})
	}
}

// TestE2E_LogsSSE verifies logs SSE works
func TestE2E_LogsSSE(t *testing.T) {
	client := testServer.httpClientWithResolver()

	// First make a request to generate a log
	client.Get(fmt.Sprintf("https://api.test.localhost:%d/", e2eHTTPSPort))

	// Connect to logs SSE
	req, err := http.NewRequest("GET", fmt.Sprintf("https://%s:%d/_api/logs/events", e2eDashboardHost, e2eHTTPSPort), nil)
	if err != nil {
		t.Fatalf("Failed to create request: %v", err)
	}

	resp, err := client.Do(req)
	if err != nil {
		t.Fatalf("Failed to connect to logs SSE: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		t.Errorf("Status = %d, want %d", resp.StatusCode, http.StatusOK)
	}

	contentType := resp.Header.Get("Content-Type")
	if contentType != "text/event-stream" {
		t.Errorf("Content-Type = %q, want 'text/event-stream'", contentType)
	}

	// Read some events
	scanner := bufio.NewScanner(resp.Body)
	timeout := time.After(2 * time.Second)
	done := make(chan bool)

	go func() {
		for scanner.Scan() {
			line := scanner.Text()
			if strings.HasPrefix(line, "event: log") {
				done <- true
				return
			}
		}
		done <- false
	}()

	select {
	case <-done:
		// Got a log event, good
	case <-timeout:
		// Timeout is OK - may not have any logs if previous request didn't complete
		t.Log("No log events received within timeout (this may be OK)")
	}
}

// TestE2E_StaticAssets verifies static assets are served correctly
func TestE2E_StaticAssets(t *testing.T) {
	client := testServer.httpClientWithResolver()

	assets := []struct {
		path        string
		contentType string
	}{
		{"/_assets/petite-vue.min.js", "application/javascript"},
		{"/_assets/theme.css", "text/css"},
		{"/_assets/favicon.svg", "image/svg+xml"},
	}

	for _, asset := range assets {
		t.Run(asset.path, func(t *testing.T) {
			resp, err := client.Get(fmt.Sprintf("https://%s:%d%s", e2eDashboardHost, e2eHTTPSPort, asset.path))
			if err != nil {
				t.Fatalf("Failed to get asset: %v", err)
			}
			defer resp.Body.Close()

			if resp.StatusCode != http.StatusOK {
				t.Errorf("Status = %d, want %d", resp.StatusCode, http.StatusOK)
			}

			contentType := resp.Header.Get("Content-Type")
			if contentType != asset.contentType {
				t.Errorf("Content-Type = %q, want %q", contentType, asset.contentType)
			}

			// Check caching header
			cacheControl := resp.Header.Get("Cache-Control")
			if !strings.Contains(cacheControl, "max-age") {
				t.Errorf("Expected Cache-Control with max-age, got %q", cacheControl)
			}
		})
	}
}

// TestE2E_NotFound verifies 404 handling
func TestE2E_NotFound(t *testing.T) {
	client := testServer.httpClientWithResolver()

	resp, err := client.Get(fmt.Sprintf("https://unknown.test.localhost:%d/", e2eHTTPSPort))
	if err != nil {
		t.Fatalf("Failed to make request: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusNotFound {
		t.Errorf("Status = %d, want %d", resp.StatusCode, http.StatusNotFound)
	}

	body, _ := io.ReadAll(resp.Body)
	if !strings.Contains(string(body), "No Route Found") {
		t.Error("404 page should contain 'No Route Found'")
	}
}
