// Package tunnel runs a Cloudflare Tunnel in front of roji, so selected routes
// can be reached from outside the machine.
//
// cloudflared is driven as a child process rather than linked as a library:
// importing it pulls in a QUIC stack and several megabytes of binary for a
// feature most runs never turn on. roji already shells out to `docker compose`
// for the same reason.
package tunnel

import (
	"bufio"
	"fmt"
	"io"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"time"
)

// Binary is the cloudflared executable, looked up on PATH.
const Binary = "cloudflared"

// stopTimeout is how long a signalled cloudflared has to exit before it is
// killed. It only has to close its connections to Cloudflare's edge.
const stopTimeout = 5 * time.Second

// Config describes the tunnel to run.
type Config struct {
	// Domain is the Cloudflare zone, e.g. "example.com".
	Domain string
	// Name is the named tunnel, created beforehand with `cloudflared tunnel create`.
	Name string
	// Port is the loopback port cloudflared forwards to.
	Port int
	// ConfigPath is where the generated cloudflared configuration is written.
	ConfigPath string
}

// LookPath returns the cloudflared executable, or an error naming what to
// install when it is not on PATH.
func LookPath() (string, error) {
	path, err := exec.LookPath(Binary)
	if err != nil {
		return "", fmt.Errorf("%s not found in PATH: %w", Binary, err)
	}
	return path, nil
}

// RenderConfig returns the cloudflared configuration for cfg.
//
// One catch-all ingress rule, never a rule per route: roji resolves hostnames
// itself, and cloudflared has no way to reload its configuration short of a
// restart. A rule per route would mean restarting the tunnel — and dropping
// every connection through it — each time a container starts or stops.
//
// The wildcard covers one level, which is all Cloudflare's Universal SSL
// certificate does. The trailing rule answers anything the wildcard misses,
// and cloudflared refuses to start without it.
func RenderConfig(cfg Config) string {
	var b strings.Builder
	b.WriteString("# Generated by roji. Edits here are overwritten on the next start.\n")
	fmt.Fprintf(&b, "tunnel: %s\n", cfg.Name)
	b.WriteString("ingress:\n")
	fmt.Fprintf(&b, "  - hostname: %q\n", "*."+cfg.Domain)
	fmt.Fprintf(&b, "    service: http://127.0.0.1:%d\n", cfg.Port)
	b.WriteString("  - service: http_status:404\n")
	return b.String()
}

// WriteConfig writes the generated cloudflared configuration for cfg.
func WriteConfig(cfg Config) error {
	if err := os.MkdirAll(filepath.Dir(cfg.ConfigPath), 0755); err != nil {
		return fmt.Errorf("failed to create directory for %s: %w", cfg.ConfigPath, err)
	}
	if err := os.WriteFile(cfg.ConfigPath, []byte(RenderConfig(cfg)), 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", cfg.ConfigPath, err)
	}
	return nil
}

// Runner supervises one cloudflared process.
//
// A crashed tunnel is reported and left down. Restarting it is the job of
// whatever supervises roji itself: roji is not a process manager, and a tunnel
// that keeps failing to authenticate would otherwise retry forever in silence.
type Runner struct {
	cfg Config

	mu       sync.Mutex
	cmd      *exec.Cmd
	stopped  chan struct{} // closed once the process has been reaped
	stopping bool          // whether the exit about to be reported was asked for
}

// NewRunner creates a Runner for cfg.
func NewRunner(cfg Config) *Runner {
	return &Runner{cfg: cfg}
}

// Start writes the configuration and launches cloudflared.
//
// It returns once the process has been spawned, not once the tunnel is
// established: cloudflared reports its own progress, and roji has no way to
// wait for a connection to Cloudflare's edge that would not also hang startup
// when the network is down.
//
// The process is deliberately not tied to a context. Stop owns its lifetime,
// and a context would end it with SIGKILL at exactly the moment shutdown wants
// to signal it instead — see Stop.
func (r *Runner) Start() error {
	r.mu.Lock()
	defer r.mu.Unlock()

	if r.cmd != nil {
		return fmt.Errorf("tunnel is already running")
	}

	bin, err := LookPath()
	if err != nil {
		return err
	}
	if err := WriteConfig(r.cfg); err != nil {
		return err
	}

	// --no-autoupdate: a tunnel that replaces its own binary and restarts is a
	// surprise in the middle of a development session.
	cmd := exec.Command(bin,
		"tunnel", "--config", r.cfg.ConfigPath, "--no-autoupdate", "run", r.cfg.Name)

	// cloudflared writes everything to stderr; stdout is merged in so nothing
	// it says is lost if that changes.
	output, err := cmd.StderrPipe()
	if err != nil {
		return fmt.Errorf("failed to capture %s output: %w", Binary, err)
	}
	cmd.Stdout = cmd.Stderr

	if err := cmd.Start(); err != nil {
		return fmt.Errorf("failed to start %s: %w", Binary, err)
	}

	slog.Info("tunnel started",
		"tunnel", r.cfg.Name,
		"domain", r.cfg.Domain,
		"target", fmt.Sprintf("http://127.0.0.1:%d", r.cfg.Port),
		"pid", cmd.Process.Pid)

	r.cmd = cmd
	r.stopped = make(chan struct{})
	r.stopping = false

	outputDone := make(chan struct{})
	go func() {
		forwardOutput(output)
		close(outputDone)
	}()
	go r.reap(cmd, r.stopped, outputDone)

	return nil
}

// reap waits for cmd and reports how it ended.
func (r *Runner) reap(cmd *exec.Cmd, stopped chan struct{}, outputDone <-chan struct{}) {
	// Wait closes the output pipe as it reaps, so reading has to finish first.
	// The lines at stake are the last ones cloudflared writes, which are the
	// ones saying why it is going away.
	<-outputDone
	err := cmd.Wait()

	r.mu.Lock()
	if r.cmd == cmd {
		r.cmd = nil
	}
	stopping := r.stopping
	r.mu.Unlock()

	// Closed after the process is cleared, so a Start issued the moment Stop
	// returns does not find the finished process still recorded.
	close(stopped)

	switch {
	case stopping:
		slog.Info("tunnel stopped", "tunnel", r.cfg.Name)
	case err != nil:
		slog.Error("tunnel exited", "tunnel", r.cfg.Name, "error", err)
	default:
		slog.Warn("tunnel exited", "tunnel", r.cfg.Name)
	}
}

// Stop shuts cloudflared down, waiting for it to close its connections.
//
// Signalling first rather than killing outright lets cloudflared tell
// Cloudflare's edge it is going away, so requests in flight are not cut off and
// the next start does not race an old registration. A process that ignores the
// signal is killed once stopTimeout passes.
func (r *Runner) Stop() {
	r.mu.Lock()
	cmd, stopped := r.cmd, r.stopped
	if cmd == nil || cmd.Process == nil {
		r.mu.Unlock()
		return
	}
	r.stopping = true
	r.mu.Unlock()

	// os.Interrupt is not implemented on Windows, where killing is the only
	// option roji has.
	if err := cmd.Process.Signal(os.Interrupt); err != nil {
		_ = cmd.Process.Kill()
	}

	select {
	case <-stopped:
	case <-time.After(stopTimeout):
		slog.Warn("tunnel did not stop in time, killing", "tunnel", r.cfg.Name)
		_ = cmd.Process.Kill()
		<-stopped
	}
}

// forwardOutput relays cloudflared's own logging into roji's.
func forwardOutput(out io.Reader) {
	scanner := bufio.NewScanner(out)
	// cloudflared logs one JSON object per line, and a line carrying an ingress
	// rule or a stack trace can pass the 64KB default. Ending the relay on the
	// longest line is the wrong way to fail.
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for scanner.Scan() {
		slog.Info("cloudflared", "line", scanner.Text())
	}
	if err := scanner.Err(); err != nil {
		slog.Warn("stopped reading cloudflared output", "error", err)
	}
}
