// Package roji embeds the license texts shipped with the roji binary.
//
// An embed pattern cannot reach files in a parent directory, so the
// embedding lives here at the module root, next to the files themselves.
package roji

import _ "embed"

// License is roji's own license.
//
//go:embed LICENSE
var License string

// Credits holds the licenses of the Go modules linked into the binary,
// generated by `go tool gocredits -w .`.
//
//go:embed CREDITS
var Credits string

// ThirdPartyNotices covers what gocredits does not collect.
//
//go:embed THIRD_PARTY_NOTICES
var ThirdPartyNotices string
