package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/fatih/color"
	"github.com/kan/roji/certgen"
	"github.com/kan/roji/config"
	"github.com/spf13/cobra"
)

var (
	caInstallUser    bool
	caInstallFirefox bool
	caInstallWindows bool
	caInstallForce   bool
)

var caInstallCmd = &cobra.Command{
	Use:   "install",
	Short: "Install CA certificate to system trust store",
	Long: `Install the roji CA certificate to the system trust store.

This allows browsers and other applications to trust HTTPS certificates
generated by roji without showing security warnings.

On macOS:
  - Installs to System Keychain (requires sudo)
  - Use --user to install to login keychain (no sudo)

On Linux:
  - Installs to system CA store (requires sudo)
  - Use --firefox to also install to Firefox's NSS store

On Linux (WSL):
  - Use --windows to install to Windows certificate store
  - Use --windows --user to install to Windows user store (no admin)

On Windows:
  - Installs to Machine certificate store (requires admin)
  - Use --user to install to User certificate store (no admin)`,
	RunE: runCAInstall,
}

func init() {
	caCmd.AddCommand(caInstallCmd)
	caInstallCmd.Flags().BoolVar(&caInstallUser, "user", false,
		"Install to user store instead of system store (macOS/Windows only)")
	caInstallCmd.Flags().BoolVar(&caInstallFirefox, "firefox", false,
		"Also install to Firefox's certificate store (Linux only, requires nss-tools)")
	caInstallCmd.Flags().BoolVar(&caInstallWindows, "windows", false,
		"Install to Windows certificate store (WSL only)")
	caInstallCmd.Flags().BoolVar(&caInstallForce, "force", false,
		"Force install even if a certificate with the same name exists")
}

func runCAInstall(cmd *cobra.Command, args []string) error {
	// Load configuration
	overrides := collectCLIOverrides(cmd)
	settings, err := config.Load(configFile, overrides)
	if err != nil {
		return fmt.Errorf("failed to load configuration: %w", err)
	}

	certsDir := settings.CertsDir
	caCertPath := filepath.Join(certsDir, "ca.pem")

	green := color.New(color.FgGreen).SprintFunc()
	red := color.New(color.FgRed).SprintFunc()

	// Check if CA certificate exists
	if _, err := os.Stat(caCertPath); os.IsNotExist(err) {
		fmt.Printf("%s CA certificate not found at: %s\n", red("✗"), caCertPath)
		fmt.Println()
		fmt.Println("Run 'roji' to auto-generate certificates first.")
		return nil
	}

	// Get the appropriate installer
	var installer certgen.CAInstaller
	if caInstallWindows {
		// Install to Windows from WSL
		if !certgen.IsWSL() {
			fmt.Printf("%s --windows flag is only available on WSL\n", red("✗"))
			return nil
		}
		// WSL always uses user store (cannot elevate to admin)
		installer = certgen.NewWSLInstaller()
	} else if caInstallUser {
		installer = certgen.NewUserInstaller()
	} else {
		installer = certgen.NewSystemInstaller()
	}

	// Check if already installed (skip if --force)
	if !caInstallForce {
		installed, _ := installer.IsInstalled(caCertPath)
		if installed {
			fmt.Printf("%s CA certificate is already installed\n", green("✓"))
			fmt.Printf("  %s\n", installer.Description())
			fmt.Println()
			fmt.Println("Use --force to reinstall/replace the certificate.")
			return nil
		}
	}

	// Show what we're about to do
	fmt.Printf("Installing CA certificate to: %s\n", installer.Description())
	if installer.NeedsSudo() {
		fmt.Println("This operation requires elevated privileges.")
	}
	fmt.Println()

	// Install the certificate
	if err := installer.Install(caCertPath); err != nil {
		return fmt.Errorf("failed to install CA certificate: %w", err)
	}

	fmt.Printf("%s CA certificate installed successfully\n", green("✓"))
	fmt.Println()

	// Optionally install to Firefox (Linux only)
	if caInstallFirefox {
		fmt.Println("Installing to Firefox...")
		ffInstaller := certgen.NewFirefoxInstaller()
		if err := ffInstaller.Install(caCertPath); err != nil {
			fmt.Printf("%s Failed to install to Firefox: %v\n", red("✗"), err)
		} else {
			fmt.Printf("%s Installed to Firefox\n", green("✓"))
		}
		fmt.Println()
	}

	fmt.Println("You may need to restart your browser for changes to take effect.")
	fmt.Println()

	return nil
}
