package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/fatih/color"
	"github.com/kan/roji/certgen"
	"github.com/kan/roji/config"
	"github.com/kan/roji/i18n"
	"github.com/spf13/cobra"
)

var (
	caInstallUser    bool
	caInstallFirefox bool
	caInstallWindows bool
	caInstallForce   bool
)

var caInstallCmd = &cobra.Command{
	Use:   "install",
	Short: "Install CA certificate to system trust store",
	Long: `Install the roji CA certificate to the system trust store.

This allows browsers and other applications to trust HTTPS certificates
generated by roji without showing security warnings.

On macOS:
  - Installs to System Keychain (requires sudo)
  - Use --user to install to login keychain (no sudo)

On Linux:
  - Installs to system CA store (requires sudo)
  - Use --firefox to also install to Firefox's NSS store

On Linux (WSL):
  - Use --windows to install to Windows certificate store
  - Use --windows --user to install to Windows user store (no admin)

On Windows:
  - Installs to Machine certificate store (requires admin)
  - Use --user to install to User certificate store (no admin)`,
	RunE: runCAInstall,
}

func init() {
	caCmd.AddCommand(caInstallCmd)
	caInstallCmd.Flags().BoolVar(&caInstallUser, "user", false,
		"Install to user store instead of system store (macOS/Windows only)")
	caInstallCmd.Flags().BoolVar(&caInstallFirefox, "firefox", false,
		"Also install to Firefox's certificate store (Linux only, requires nss-tools)")
	caInstallCmd.Flags().BoolVar(&caInstallWindows, "windows", false,
		"Install to Windows certificate store (WSL only)")
	caInstallCmd.Flags().BoolVar(&caInstallForce, "force", false,
		"Force install even if a certificate with the same name exists")
}

func runCAInstall(cmd *cobra.Command, args []string) error {
	// Load configuration
	overrides := collectCLIOverrides(cmd)
	settings, err := config.Load(configFile, overrides)
	if err != nil {
		return fmt.Errorf("failed to load configuration: %w", err)
	}

	certsDir := settings.CertsDir
	caCertPath := filepath.Join(certsDir, "ca.pem")

	green := color.New(color.FgGreen).SprintFunc()
	red := color.New(color.FgRed).SprintFunc()

	// Check if CA certificate exists
	if _, err := os.Stat(caCertPath); os.IsNotExist(err) {
		fmt.Printf("%s %s\n", red("✗"), i18n.Tf("cmd.ca.install.not_found", caCertPath))
		fmt.Println()
		fmt.Println(i18n.T("cmd.ca.install.generate_hint"))
		return nil
	}

	// Get the appropriate installer
	var installer certgen.CAInstaller
	if caInstallWindows {
		// Install to Windows from WSL
		if !certgen.IsWSL() {
			fmt.Printf("%s %s\n", red("✗"), i18n.T("cmd.ca.install.wsl_only"))
			return nil
		}
		// WSL always uses user store (cannot elevate to admin)
		installer = certgen.NewWSLInstaller()
	} else if caInstallUser {
		installer = certgen.NewUserInstaller()
	} else {
		installer = certgen.NewSystemInstaller()
	}

	// Check if already installed (skip if --force)
	if !caInstallForce {
		installed, _ := installer.IsInstalled(caCertPath)
		if installed {
			fmt.Printf("%s %s\n", green("✓"), i18n.T("cmd.ca.install.already_installed"))
			fmt.Printf("  %s\n", installer.Description())
			fmt.Println()
			fmt.Println(i18n.T("cmd.ca.install.force_hint"))
			return nil
		}
	}

	// Show what we're about to do
	fmt.Println(i18n.Tf("cmd.ca.install.installing", installer.Description()))
	if installer.NeedsSudo() {
		fmt.Println(i18n.T("cmd.ca.install.needs_sudo"))
	}
	fmt.Println()

	// Install the certificate
	if err := installer.Install(caCertPath); err != nil {
		return fmt.Errorf("failed to install CA certificate: %w", err)
	}

	fmt.Printf("%s %s\n", green("✓"), i18n.T("cmd.ca.install.success"))
	fmt.Println()

	// Optionally install to Firefox (Linux only)
	if caInstallFirefox {
		fmt.Println(i18n.T("cmd.ca.install.firefox_installing"))
		ffInstaller := certgen.NewFirefoxInstaller()
		if err := ffInstaller.Install(caCertPath); err != nil {
			fmt.Printf("%s %s\n", red("✗"), i18n.Tf("cmd.ca.install.firefox_failed", err))
		} else {
			fmt.Printf("%s %s\n", green("✓"), i18n.T("cmd.ca.install.firefox_success"))
		}
		fmt.Println()
	}

	fmt.Println(i18n.T("cmd.ca.install.restart_hint"))
	fmt.Println()

	return nil
}
