package proxy

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/kan/roji/docker"
)

func testStatusConfig() *StatusConfig {
	return &StatusConfig{
		Version:       "test",
		StartTime:     time.Now(),
		CertsDir:      "/tmp/certs",
		AutoGenerated: true,
		Networks:      []string{"roji"},
		BaseDomain:    "dev.localhost",
		HTTPPort:      80,
		HTTPSPort:     443,
	}
}

func TestHandler_ServeHTTP_NotFound(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	req := httptest.NewRequest("GET", "https://unknown.localhost/", nil)
	req.Host = "unknown.localhost"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	if w.Code != http.StatusNotFound {
		t.Errorf("status = %d, want %d", w.Code, http.StatusNotFound)
	}

	body := w.Body.String()
	if !strings.Contains(body, "No Route Found") {
		t.Errorf("body should contain 'No Route Found', got %q", body)
	}
}

func TestHandler_ServeHTTP_Dashboard(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	req := httptest.NewRequest("GET", "https://roji.dev.localhost/", nil)
	req.Host = "roji.dev.localhost"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("status = %d, want %d", w.Code, http.StatusOK)
	}

	body := w.Body.String()
	if !strings.Contains(body, "roji") {
		t.Errorf("dashboard should contain 'roji', got %q", body)
	}
	if !strings.Contains(body, "reverse proxy") {
		t.Errorf("dashboard should contain 'reverse proxy'")
	}
}

func TestHandler_ServeHTTP_DashboardWithRoutes(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	// Add a route
	backend := &docker.Backend{
		ContainerID:   "abc123",
		ContainerName: "web",
		ServiceName:   "web",
		Host:          "172.17.0.2",
		Port:          80,
		Hostname:      "web.localhost",
	}
	router.AddBackend(backend)

	req := httptest.NewRequest("GET", "https://roji.dev.localhost/", nil)
	req.Host = "roji.dev.localhost"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	body := w.Body.String()
	if !strings.Contains(body, "web.localhost") {
		t.Errorf("dashboard should show registered route 'web.localhost'")
	}
	if !strings.Contains(body, "1") {
		t.Errorf("dashboard should show route count")
	}
}

func TestHandler_ServeHTTP_RouteExists(t *testing.T) {
	router := NewRouter()
	_ = NewHandler(router, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	// Add a route
	backend := &docker.Backend{
		ContainerID:   "abc123",
		ContainerName: "web",
		ServiceName:   "web",
		Host:          "172.17.0.2",
		Port:          80,
		Hostname:      "web.localhost",
	}
	router.AddBackend(backend)

	// Verify the route exists (actual proxy test requires real network)
	route := router.Lookup("web.localhost", "/")
	if route == nil {
		t.Fatal("route should exist")
	}
	if route.Backend.Host != "172.17.0.2" {
		t.Errorf("backend host = %q, want %q", route.Backend.Host, "172.17.0.2")
	}
}

func TestHandler_CaseInsensitiveHostname(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, "ROJI.DEV.LOCALHOST", "DEV.LOCALHOST", testStatusConfig(), nil)

	// Dashboard should work with uppercase
	req := httptest.NewRequest("GET", "https://ROJI.DEV.LOCALHOST/", nil)
	req.Host = "ROJI.DEV.LOCALHOST"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("status = %d, want %d for uppercase hostname", w.Code, http.StatusOK)
	}
}

func TestHandler_HostnameWithPort(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	// Should strip port from hostname
	req := httptest.NewRequest("GET", "https://roji.dev.localhost:443/", nil)
	req.Host = "roji.dev.localhost:443"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("status = %d, want %d when hostname includes port", w.Code, http.StatusOK)
	}
}

func TestRedirectHandler(t *testing.T) {
	tests := []struct {
		name        string
		httpsPort   int
		host        string
		path        string
		expectedURL string
	}{
		{
			name:        "standard port",
			httpsPort:   443,
			host:        "api.localhost",
			path:        "/users",
			expectedURL: "https://api.localhost/users",
		},
		{
			name:        "custom port",
			httpsPort:   8443,
			host:        "api.localhost",
			path:        "/users",
			expectedURL: "https://api.localhost:8443/users",
		},
		{
			name:        "host with port",
			httpsPort:   443,
			host:        "api.localhost:80",
			path:        "/",
			expectedURL: "https://api.localhost/",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			handler := &RedirectHandler{HTTPSPort: tt.httpsPort}

			req := httptest.NewRequest("GET", "http://"+tt.host+tt.path, nil)
			req.Host = tt.host
			w := httptest.NewRecorder()

			handler.ServeHTTP(w, req)

			if w.Code != http.StatusMovedPermanently {
				t.Errorf("status = %d, want %d", w.Code, http.StatusMovedPermanently)
			}

			location := w.Header().Get("Location")
			if location != tt.expectedURL {
				t.Errorf("Location = %q, want %q", location, tt.expectedURL)
			}
		})
	}
}

func TestHandler_Assets(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	req := httptest.NewRequest("GET", "https://roji.dev.localhost/_assets/petite-vue.min.js", nil)
	req.Host = "roji.dev.localhost"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("status = %d, want %d", w.Code, http.StatusOK)
	}
	if ct := w.Header().Get("Content-Type"); ct != "application/javascript" {
		t.Errorf("Content-Type = %q, want %q", ct, "application/javascript")
	}
	if cc := w.Header().Get("Cache-Control"); !strings.Contains(cc, "max-age") {
		t.Errorf("Cache-Control should contain max-age, got %q", cc)
	}
}

func TestHandler_Assets_NotFound(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	req := httptest.NewRequest("GET", "https://roji.dev.localhost/_assets/nonexistent.js", nil)
	req.Host = "roji.dev.localhost"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	if w.Code != http.StatusNotFound {
		t.Errorf("status = %d, want %d", w.Code, http.StatusNotFound)
	}
}

func TestHandler_Assets_PathTraversal(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	tests := []string{
		"/_assets/../handler.go",
		"/_assets/../../go.mod",
		"/_assets/foo/bar.js",
	}

	for _, path := range tests {
		t.Run(path, func(t *testing.T) {
			req := httptest.NewRequest("GET", "https://roji.dev.localhost"+path, nil)
			req.Host = "roji.dev.localhost"
			w := httptest.NewRecorder()

			handler.ServeHTTP(w, req)

			if w.Code != http.StatusNotFound {
				t.Errorf("path %q: status = %d, want %d", path, w.Code, http.StatusNotFound)
			}
		})
	}
}

func TestHandler_SSE_Headers(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	// Create request with cancellable context
	ctx, cancel := context.WithCancel(context.Background())
	req := httptest.NewRequest("GET", "https://roji.dev.localhost/_api/events", nil)
	req = req.WithContext(ctx)
	req.Host = "roji.dev.localhost"
	w := httptest.NewRecorder()

	// Run handler in goroutine since it blocks
	done := make(chan struct{})
	go func() {
		handler.ServeHTTP(w, req)
		close(done)
	}()

	// Cancel the context to stop the SSE handler
	time.Sleep(50 * time.Millisecond)
	cancel()

	// Wait for handler to complete before reading headers
	<-done

	// Verify SSE headers
	if ct := w.Header().Get("Content-Type"); ct != "text/event-stream" {
		t.Errorf("Content-Type = %q, want %q", ct, "text/event-stream")
	}
	if cc := w.Header().Get("Cache-Control"); cc != "no-cache" {
		t.Errorf("Cache-Control = %q, want %q", cc, "no-cache")
	}
}

func TestHandler_RoutesAPI(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	// Add a route
	backend := &docker.Backend{
		ContainerID:   "abc123",
		ContainerName: "web",
		ServiceName:   "web",
		Host:          "172.17.0.2",
		Port:          80,
		Hostname:      "web.localhost",
	}
	router.AddBackend(backend)

	req := httptest.NewRequest("GET", "https://roji.dev.localhost/_api/routes", nil)
	req.Host = "roji.dev.localhost"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("status = %d, want %d", w.Code, http.StatusOK)
	}
	if ct := w.Header().Get("Content-Type"); ct != "application/json" {
		t.Errorf("Content-Type = %q, want %q", ct, "application/json")
	}

	body := w.Body.String()
	if !strings.Contains(body, "web.localhost") {
		t.Errorf("response should contain route hostname, got %q", body)
	}
}

func TestHandler_StatusAPI(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	req := httptest.NewRequest("GET", "https://roji.dev.localhost/_api/status", nil)
	req.Host = "roji.dev.localhost"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("status = %d, want %d", w.Code, http.StatusOK)
	}

	body := w.Body.String()
	if !strings.Contains(body, "sse_subscribers") {
		t.Errorf("status response should contain sse_subscribers, got %q", body)
	}
}

func TestHandler_ProjectsAPI_NilStore(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	req := httptest.NewRequest("GET", "https://roji.dev.localhost/_api/projects", nil)
	req.Host = "roji.dev.localhost"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("status = %d, want %d", w.Code, http.StatusOK)
	}
	if ct := w.Header().Get("Content-Type"); ct != "application/json" {
		t.Errorf("Content-Type = %q, want %q", ct, "application/json")
	}

	body := w.Body.String()
	if !strings.Contains(body, `"active":[]`) {
		t.Errorf("response should contain empty active array, got %q", body)
	}
	if !strings.Contains(body, `"inactive":[]`) {
		t.Errorf("response should contain empty inactive array, got %q", body)
	}
}

func TestHandler_BaseDomainRedirect(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	// Test that base domain redirects to dashboard host
	req := httptest.NewRequest("GET", "https://dev.localhost/", nil)
	req.Host = "dev.localhost"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	if w.Code != http.StatusFound {
		t.Errorf("status = %d, want %d (302 redirect)", w.Code, http.StatusFound)
	}

	location := w.Header().Get("Location")
	expectedLocation := "https://roji.dev.localhost/"
	if location != expectedLocation {
		t.Errorf("Location = %q, want %q", location, expectedLocation)
	}
}

func TestHandler_BaseDomainRedirectWithPath(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	tests := []struct {
		name             string
		path             string
		expectedLocation string
	}{
		{
			name:             "root path",
			path:             "/",
			expectedLocation: "https://roji.dev.localhost/",
		},
		{
			name:             "with query string",
			path:             "/?foo=bar",
			expectedLocation: "https://roji.dev.localhost/?foo=bar",
		},
		{
			name:             "api endpoint",
			path:             "/_api/routes",
			expectedLocation: "https://roji.dev.localhost/_api/routes",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			req := httptest.NewRequest("GET", "https://dev.localhost"+tt.path, nil)
			req.Host = "dev.localhost"
			w := httptest.NewRecorder()

			handler.ServeHTTP(w, req)

			if w.Code != http.StatusFound {
				t.Errorf("%s: status = %d, want %d", tt.name, w.Code, http.StatusFound)
			}

			location := w.Header().Get("Location")
			if location != tt.expectedLocation {
				t.Errorf("%s: Location = %q, want %q", tt.name, location, tt.expectedLocation)
			}
		})
	}
}

func TestHandler_DashboardHostNoRedirect(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	// Dashboard host should NOT redirect
	req := httptest.NewRequest("GET", "https://roji.dev.localhost/", nil)
	req.Host = "roji.dev.localhost"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("status = %d, want %d (should not redirect)", w.Code, http.StatusOK)
	}

	body := w.Body.String()
	if !strings.Contains(body, "roji") {
		t.Errorf("dashboard should contain 'roji'")
	}
}
