package proxy

import (
	"context"
	"net"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strconv"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/gorilla/websocket"
	"github.com/kan/roji/config"
	"github.com/kan/roji/docker"
	"github.com/kan/roji/project"
)

func testStatusConfig() *StatusConfig {
	return &StatusConfig{
		Version:       "test",
		StartTime:     time.Now(),
		CertsDir:      "/tmp/certs",
		AutoGenerated: true,
		Networks:      []string{"roji"},
		BaseDomain:    "dev.localhost",
		HTTPPort:      80,
		HTTPSPort:     443,
	}
}

func TestHandler_ServeHTTP_NotFound(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	req := httptest.NewRequest("GET", "https://unknown.localhost/", nil)
	req.Host = "unknown.localhost"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	if w.Code != http.StatusNotFound {
		t.Errorf("status = %d, want %d", w.Code, http.StatusNotFound)
	}

	body := w.Body.String()
	if !strings.Contains(body, "No Route Found") {
		t.Errorf("body should contain 'No Route Found', got %q", body)
	}
}

func TestHandler_ServeHTTP_Dashboard(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	req := httptest.NewRequest("GET", "https://roji.dev.localhost/", nil)
	req.Host = "roji.dev.localhost"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("status = %d, want %d", w.Code, http.StatusOK)
	}

	body := w.Body.String()
	if !strings.Contains(body, "roji") {
		t.Errorf("dashboard should contain 'roji', got %q", body)
	}
	if !strings.Contains(body, "reverse proxy") {
		t.Errorf("dashboard should contain 'reverse proxy'")
	}
}

func TestHandler_ServeHTTP_DashboardEmptyRoutes(t *testing.T) {
	// Test that dashboard renders correctly when no containers are connected
	// This prevents the JavaScript error: "Cannot read properties of null (reading 'forEach')"
	router := NewRouter()
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	req := httptest.NewRequest("GET", "https://roji.dev.localhost/", nil)
	req.Host = "roji.dev.localhost"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("status = %d, want %d", w.Code, http.StatusOK)
	}

	body := w.Body.String()

	// Verify routes is initialized as empty array, not null
	// This is critical for Petite Vue to work correctly
	if !strings.Contains(body, "routes: []") {
		t.Errorf("dashboard should initialize routes as empty array '[]', not null")
	}

	// Verify the dashboard HTML structure is present
	if !strings.Contains(body, "PetiteVue") {
		t.Errorf("dashboard should contain PetiteVue initialization")
	}
}

func TestHandler_ServeHTTP_DashboardWithRoutes(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	// Add a route
	backend := &docker.Backend{
		ContainerID:   "abc123",
		ContainerName: "web",
		ServiceName:   "web",
		Host:          "172.17.0.2",
		Port:          80,
		Hostname:      "web.localhost",
	}
	router.AddBackend(backend)

	req := httptest.NewRequest("GET", "https://roji.dev.localhost/", nil)
	req.Host = "roji.dev.localhost"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	body := w.Body.String()
	if !strings.Contains(body, "web.localhost") {
		t.Errorf("dashboard should show registered route 'web.localhost'")
	}
	if !strings.Contains(body, "1") {
		t.Errorf("dashboard should show route count")
	}
}

func TestHandler_ServeHTTP_RouteExists(t *testing.T) {
	router := NewRouter()
	_ = NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	// Add a route
	backend := &docker.Backend{
		ContainerID:   "abc123",
		ContainerName: "web",
		ServiceName:   "web",
		Host:          "172.17.0.2",
		Port:          80,
		Hostname:      "web.localhost",
	}
	router.AddBackend(backend)

	// Verify the route exists (actual proxy test requires real network)
	route := router.Lookup("web.localhost", "/")
	if route == nil {
		t.Fatal("route should exist")
	}
	if route.Backend.Host != "172.17.0.2" {
		t.Errorf("backend host = %q, want %q", route.Backend.Host, "172.17.0.2")
	}
}

func TestHandler_CaseInsensitiveHostname(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, nil, "ROJI.DEV.LOCALHOST", "DEV.LOCALHOST", testStatusConfig(), nil)

	// Dashboard should work with uppercase
	req := httptest.NewRequest("GET", "https://ROJI.DEV.LOCALHOST/", nil)
	req.Host = "ROJI.DEV.LOCALHOST"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("status = %d, want %d for uppercase hostname", w.Code, http.StatusOK)
	}
}

func TestHandler_HostnameWithPort(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	// Should strip port from hostname
	req := httptest.NewRequest("GET", "https://roji.dev.localhost:443/", nil)
	req.Host = "roji.dev.localhost:443"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("status = %d, want %d when hostname includes port", w.Code, http.StatusOK)
	}
}

func TestRedirectHandler(t *testing.T) {
	tests := []struct {
		name        string
		httpsPort   int
		host        string
		path        string
		expectedURL string
	}{
		{
			name:        "standard port",
			httpsPort:   443,
			host:        "api.localhost",
			path:        "/users",
			expectedURL: "https://api.localhost/users",
		},
		{
			name:        "custom port",
			httpsPort:   8443,
			host:        "api.localhost",
			path:        "/users",
			expectedURL: "https://api.localhost:8443/users",
		},
		{
			name:        "host with port",
			httpsPort:   443,
			host:        "api.localhost:80",
			path:        "/",
			expectedURL: "https://api.localhost/",
		},
		{
			name:        "IPv6 host keeps its brackets",
			httpsPort:   443,
			host:        "[::1]",
			path:        "/",
			expectedURL: "https://[::1]/",
		},
		{
			name:        "IPv6 host with port",
			httpsPort:   8443,
			host:        "[::1]:80",
			path:        "/users",
			expectedURL: "https://[::1]:8443/users",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			handler := &RedirectHandler{HTTPSPort: tt.httpsPort}

			req := httptest.NewRequest("GET", "http://"+tt.host+tt.path, nil)
			req.Host = tt.host
			w := httptest.NewRecorder()

			handler.ServeHTTP(w, req)

			if w.Code != http.StatusMovedPermanently {
				t.Errorf("status = %d, want %d", w.Code, http.StatusMovedPermanently)
			}

			location := w.Header().Get("Location")
			if location != tt.expectedURL {
				t.Errorf("Location = %q, want %q", location, tt.expectedURL)
			}
		})
	}
}

func TestHandler_Assets(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	req := httptest.NewRequest("GET", "https://roji.dev.localhost/_assets/petite-vue.min.js", nil)
	req.Host = "roji.dev.localhost"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("status = %d, want %d", w.Code, http.StatusOK)
	}
	if ct := w.Header().Get("Content-Type"); ct != "application/javascript" {
		t.Errorf("Content-Type = %q, want %q", ct, "application/javascript")
	}
	if cc := w.Header().Get("Cache-Control"); !strings.Contains(cc, "max-age") {
		t.Errorf("Cache-Control should contain max-age, got %q", cc)
	}
}

func TestHandler_Assets_NotFound(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	req := httptest.NewRequest("GET", "https://roji.dev.localhost/_assets/nonexistent.js", nil)
	req.Host = "roji.dev.localhost"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	if w.Code != http.StatusNotFound {
		t.Errorf("status = %d, want %d", w.Code, http.StatusNotFound)
	}
}

func TestHandler_Assets_PathTraversal(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	tests := []string{
		"/_assets/../handler.go",
		"/_assets/../../go.mod",
		"/_assets/foo/bar.js",
	}

	for _, path := range tests {
		t.Run(path, func(t *testing.T) {
			req := httptest.NewRequest("GET", "https://roji.dev.localhost"+path, nil)
			req.Host = "roji.dev.localhost"
			w := httptest.NewRecorder()

			handler.ServeHTTP(w, req)

			if w.Code != http.StatusNotFound {
				t.Errorf("path %q: status = %d, want %d", path, w.Code, http.StatusNotFound)
			}
		})
	}
}

func TestHandler_SSE_Headers(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	// Create request with cancellable context
	ctx, cancel := context.WithCancel(context.Background())
	req := httptest.NewRequest("GET", "https://roji.dev.localhost/_api/events", nil)
	req = req.WithContext(ctx)
	req.Host = "roji.dev.localhost"
	w := httptest.NewRecorder()

	// Run handler in goroutine since it blocks
	done := make(chan struct{})
	go func() {
		handler.ServeHTTP(w, req)
		close(done)
	}()

	// Cancel the context to stop the SSE handler
	time.Sleep(50 * time.Millisecond)
	cancel()

	// Wait for handler to complete before reading headers
	<-done

	// Verify SSE headers
	if ct := w.Header().Get("Content-Type"); ct != "text/event-stream" {
		t.Errorf("Content-Type = %q, want %q", ct, "text/event-stream")
	}
	if cc := w.Header().Get("Cache-Control"); cc != "no-cache" {
		t.Errorf("Cache-Control = %q, want %q", cc, "no-cache")
	}
}

func TestHandler_RoutesAPI(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	// Add a route
	backend := &docker.Backend{
		ContainerID:   "abc123",
		ContainerName: "web",
		ServiceName:   "web",
		Host:          "172.17.0.2",
		Port:          80,
		Hostname:      "web.localhost",
	}
	router.AddBackend(backend)

	req := httptest.NewRequest("GET", "https://roji.dev.localhost/_api/routes", nil)
	req.Host = "roji.dev.localhost"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("status = %d, want %d", w.Code, http.StatusOK)
	}
	if ct := w.Header().Get("Content-Type"); ct != "application/json" {
		t.Errorf("Content-Type = %q, want %q", ct, "application/json")
	}

	body := w.Body.String()
	if !strings.Contains(body, "web.localhost") {
		t.Errorf("response should contain route hostname, got %q", body)
	}
}

func TestHandler_StatusAPI(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	req := httptest.NewRequest("GET", "https://roji.dev.localhost/_api/status", nil)
	req.Host = "roji.dev.localhost"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("status = %d, want %d", w.Code, http.StatusOK)
	}

	body := w.Body.String()
	if !strings.Contains(body, "sse_subscribers") {
		t.Errorf("status response should contain sse_subscribers, got %q", body)
	}
}

func TestHandler_ProjectsAPI_NilStore(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	req := httptest.NewRequest("GET", "https://roji.dev.localhost/_api/projects", nil)
	req.Host = "roji.dev.localhost"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("status = %d, want %d", w.Code, http.StatusOK)
	}
	if ct := w.Header().Get("Content-Type"); ct != "application/json" {
		t.Errorf("Content-Type = %q, want %q", ct, "application/json")
	}

	body := w.Body.String()
	if !strings.Contains(body, `"active":[]`) {
		t.Errorf("response should contain empty active array, got %q", body)
	}
	if !strings.Contains(body, `"inactive":[]`) {
		t.Errorf("response should contain empty inactive array, got %q", body)
	}
}

func TestHandler_BaseDomainRedirect(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	// Test that base domain redirects to dashboard host
	req := httptest.NewRequest("GET", "https://dev.localhost/", nil)
	req.Host = "dev.localhost"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	if w.Code != http.StatusFound {
		t.Errorf("status = %d, want %d (302 redirect)", w.Code, http.StatusFound)
	}

	location := w.Header().Get("Location")
	expectedLocation := "https://roji.dev.localhost/"
	if location != expectedLocation {
		t.Errorf("Location = %q, want %q", location, expectedLocation)
	}
}

func TestHandler_BaseDomainRedirectWithPath(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	tests := []struct {
		name             string
		path             string
		expectedLocation string
	}{
		{
			name:             "root path",
			path:             "/",
			expectedLocation: "https://roji.dev.localhost/",
		},
		{
			name:             "with query string",
			path:             "/?foo=bar",
			expectedLocation: "https://roji.dev.localhost/?foo=bar",
		},
		{
			name:             "api endpoint",
			path:             "/_api/routes",
			expectedLocation: "https://roji.dev.localhost/_api/routes",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			req := httptest.NewRequest("GET", "https://dev.localhost"+tt.path, nil)
			req.Host = "dev.localhost"
			w := httptest.NewRecorder()

			handler.ServeHTTP(w, req)

			if w.Code != http.StatusFound {
				t.Errorf("%s: status = %d, want %d", tt.name, w.Code, http.StatusFound)
			}

			location := w.Header().Get("Location")
			if location != tt.expectedLocation {
				t.Errorf("%s: Location = %q, want %q", tt.name, location, tt.expectedLocation)
			}
		})
	}
}

func TestHandler_DashboardHostNoRedirect(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	// Dashboard host should NOT redirect
	req := httptest.NewRequest("GET", "https://roji.dev.localhost/", nil)
	req.Host = "roji.dev.localhost"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("status = %d, want %d (should not redirect)", w.Code, http.StatusOK)
	}

	body := w.Body.String()
	if !strings.Contains(body, "roji") {
		t.Errorf("dashboard should contain 'roji'")
	}
}

func TestIsWebSocketRequest(t *testing.T) {
	tests := []struct {
		name       string
		headers    map[string]string
		wantResult bool
	}{
		{
			name: "valid websocket request",
			headers: map[string]string{
				"Upgrade":    "websocket",
				"Connection": "Upgrade",
			},
			wantResult: true,
		},
		{
			name: "valid websocket request (case insensitive)",
			headers: map[string]string{
				"Upgrade":    "WebSocket",
				"Connection": "upgrade",
			},
			wantResult: true,
		},
		{
			name: "connection with multiple values",
			headers: map[string]string{
				"Upgrade":    "websocket",
				"Connection": "keep-alive, Upgrade",
			},
			wantResult: true,
		},
		{
			name: "missing upgrade header",
			headers: map[string]string{
				"Connection": "Upgrade",
			},
			wantResult: false,
		},
		{
			name: "missing connection header",
			headers: map[string]string{
				"Upgrade": "websocket",
			},
			wantResult: false,
		},
		{
			name: "wrong upgrade value",
			headers: map[string]string{
				"Upgrade":    "h2c",
				"Connection": "Upgrade",
			},
			wantResult: false,
		},
		{
			name:       "no headers",
			headers:    map[string]string{},
			wantResult: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			req := httptest.NewRequest("GET", "/ws", nil)
			for k, v := range tt.headers {
				req.Header.Set(k, v)
			}

			got := isWebSocketRequest(req)
			if got != tt.wantResult {
				t.Errorf("isWebSocketRequest() = %v, want %v", got, tt.wantResult)
			}
		})
	}
}

func TestHandler_WebSocketProxy(t *testing.T) {
	// Create a test WebSocket backend server
	backendServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		upgrader := websocket.Upgrader{
			CheckOrigin: func(r *http.Request) bool { return true },
		}
		conn, err := upgrader.Upgrade(w, r, nil)
		if err != nil {
			t.Logf("backend upgrade error: %v", err)
			return
		}
		defer conn.Close()

		// Echo messages back
		for {
			messageType, message, err := conn.ReadMessage()
			if err != nil {
				break
			}
			if err := conn.WriteMessage(messageType, message); err != nil {
				break
			}
		}
	}))
	defer backendServer.Close()

	// Setup router with route to backend
	router := NewRouter()
	addBackendFor(t, router, "ws.localhost", backendServer.URL)

	// Create handler
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	// Create test server with our handler
	proxyServer := httptest.NewServer(handler)
	defer proxyServer.Close()

	// Connect to proxy via WebSocket
	proxyURL, _ := url.Parse(proxyServer.URL)
	wsURL := "ws://" + proxyURL.Host + "/ws"

	// Create custom dialer with Host header
	dialer := websocket.Dialer{}
	header := http.Header{}
	header.Set("Host", "ws.localhost")

	conn, resp, err := dialer.Dial(wsURL, header)
	if err != nil {
		t.Fatalf("WebSocket dial failed: %v", err)
	}
	defer conn.Close()

	if resp.StatusCode != http.StatusSwitchingProtocols {
		t.Errorf("status = %d, want %d", resp.StatusCode, http.StatusSwitchingProtocols)
	}

	// Test echo
	testMessage := []byte("hello websocket")
	if err := conn.WriteMessage(websocket.TextMessage, testMessage); err != nil {
		t.Fatalf("WriteMessage failed: %v", err)
	}

	messageType, message, err := conn.ReadMessage()
	if err != nil {
		t.Fatalf("ReadMessage failed: %v", err)
	}

	if messageType != websocket.TextMessage {
		t.Errorf("messageType = %d, want %d", messageType, websocket.TextMessage)
	}
	if string(message) != string(testMessage) {
		t.Errorf("message = %q, want %q", string(message), string(testMessage))
	}
}

func TestHandler_WebSocketProxy_BackendUnavailable(t *testing.T) {
	// Setup router with route to non-existent backend
	router := NewRouter()
	backend := &docker.Backend{
		ContainerID:   "ws-test",
		ContainerName: "ws-test",
		ServiceName:   "ws-test",
		Host:          "127.0.0.1",
		Port:          59999, // Non-existent port
		Hostname:      "ws.localhost",
	}
	router.AddBackend(backend)

	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	// Create WebSocket upgrade request
	req := httptest.NewRequest("GET", "https://ws.localhost/ws", nil)
	req.Host = "ws.localhost"
	req.Header.Set("Upgrade", "websocket")
	req.Header.Set("Connection", "Upgrade")
	req.Header.Set("Sec-WebSocket-Version", "13")
	req.Header.Set("Sec-WebSocket-Key", "dGhlIHNhbXBsZSBub25jZQ==")

	w := httptest.NewRecorder()
	handler.ServeHTTP(w, req)

	// Should return Bad Gateway when backend is unavailable
	if w.Code != http.StatusBadGateway {
		t.Errorf("status = %d, want %d", w.Code, http.StatusBadGateway)
	}
}

func TestIsGRPCRequest(t *testing.T) {
	tests := []struct {
		name        string
		contentType string
		wantResult  bool
	}{
		{
			name:        "valid grpc request",
			contentType: "application/grpc",
			wantResult:  true,
		},
		{
			name:        "grpc with proto suffix",
			contentType: "application/grpc+proto",
			wantResult:  true,
		},
		{
			name:        "grpc-web",
			contentType: "application/grpc-web",
			wantResult:  true,
		},
		{
			name:        "grpc-web+proto",
			contentType: "application/grpc-web+proto",
			wantResult:  true,
		},
		{
			name:        "regular json",
			contentType: "application/json",
			wantResult:  false,
		},
		{
			name:        "empty content type",
			contentType: "",
			wantResult:  false,
		},
		{
			name:        "text/html",
			contentType: "text/html",
			wantResult:  false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			req := httptest.NewRequest("POST", "/chat.ChatService/SendMessage", nil)
			if tt.contentType != "" {
				req.Header.Set("Content-Type", tt.contentType)
			}

			got := isGRPCRequest(req)
			if got != tt.wantResult {
				t.Errorf("isGRPCRequest() = %v, want %v", got, tt.wantResult)
			}
		})
	}
}

func TestHandler_GRPCProxy_BackendUnavailable(t *testing.T) {
	// Setup router with route to non-existent backend
	router := NewRouter()
	backend := &docker.Backend{
		ContainerID:   "grpc-test",
		ContainerName: "grpc-test",
		ServiceName:   "grpc-test",
		Host:          "127.0.0.1",
		Port:          59998, // Non-existent port
		Hostname:      "grpc.localhost",
	}
	router.AddBackend(backend)

	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	// Create gRPC request
	req := httptest.NewRequest("POST", "https://grpc.localhost/chat.ChatService/GetUsers", nil)
	req.Host = "grpc.localhost"
	req.Header.Set("Content-Type", "application/grpc")
	req.Header.Set("TE", "trailers")

	w := httptest.NewRecorder()
	handler.ServeHTTP(w, req)

	// Should return Bad Gateway when backend is unavailable
	if w.Code != http.StatusBadGateway {
		t.Errorf("status = %d, want %d", w.Code, http.StatusBadGateway)
	}

	// Should have gRPC error headers
	if ct := w.Header().Get("Content-Type"); ct != "application/grpc" {
		t.Errorf("Content-Type = %q, want %q", ct, "application/grpc")
	}
	if status := w.Header().Get("Grpc-Status"); status != "14" {
		t.Errorf("Grpc-Status = %q, want %q", status, "14")
	}
}

func TestCheckBasicAuth(t *testing.T) {
	tests := []struct {
		name          string
		auth          *config.BasicAuth
		reqUser       string
		reqPass       string
		expectSuccess bool
		expectStatus  int
		expectHeader  string
	}{
		{
			name:          "no auth required",
			auth:          nil,
			reqUser:       "",
			reqPass:       "",
			expectSuccess: true,
		},
		{
			name: "correct credentials",
			auth: &config.BasicAuth{
				User:  "admin",
				Pass:  "secret",
				Realm: "Test Realm",
			},
			reqUser:       "admin",
			reqPass:       "secret",
			expectSuccess: true,
		},
		{
			name: "wrong username",
			auth: &config.BasicAuth{
				User:  "admin",
				Pass:  "secret",
				Realm: "Test Realm",
			},
			reqUser:       "wronguser",
			reqPass:       "secret",
			expectSuccess: false,
			expectStatus:  http.StatusUnauthorized,
			expectHeader:  `Basic realm="Test Realm"`,
		},
		{
			name: "wrong password",
			auth: &config.BasicAuth{
				User:  "admin",
				Pass:  "secret",
				Realm: "Test Realm",
			},
			reqUser:       "admin",
			reqPass:       "wrongpass",
			expectSuccess: false,
			expectStatus:  http.StatusUnauthorized,
			expectHeader:  `Basic realm="Test Realm"`,
		},
		{
			name: "no credentials provided",
			auth: &config.BasicAuth{
				User:  "admin",
				Pass:  "secret",
				Realm: "Test Realm",
			},
			reqUser:       "",
			reqPass:       "",
			expectSuccess: false,
			expectStatus:  http.StatusUnauthorized,
			expectHeader:  `Basic realm="Test Realm"`,
		},
		{
			name: "default realm",
			auth: &config.BasicAuth{
				User:  "admin",
				Pass:  "secret",
				Realm: "",
			},
			reqUser:       "wronguser",
			reqPass:       "wrongpass",
			expectSuccess: false,
			expectStatus:  http.StatusUnauthorized,
			expectHeader:  `Basic realm="Restricted"`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			req := httptest.NewRequest("GET", "/", nil)
			if tt.reqUser != "" || tt.reqPass != "" {
				req.SetBasicAuth(tt.reqUser, tt.reqPass)
			}
			w := httptest.NewRecorder()

			result := checkBasicAuth(w, req, tt.auth)

			if result != tt.expectSuccess {
				t.Errorf("checkBasicAuth() = %v, want %v", result, tt.expectSuccess)
			}

			if !tt.expectSuccess {
				if w.Code != tt.expectStatus {
					t.Errorf("status = %d, want %d", w.Code, tt.expectStatus)
				}
				if header := w.Header().Get("WWW-Authenticate"); header != tt.expectHeader {
					t.Errorf("WWW-Authenticate = %q, want %q", header, tt.expectHeader)
				}
			}
		})
	}
}

func TestHandler_BasicAuth_DockerRoute(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	// Add a route with basic auth
	backend := &docker.Backend{
		ContainerID:   "auth-test",
		ContainerName: "auth-test",
		ServiceName:   "auth-test",
		Host:          "127.0.0.1",
		Port:          59997, // Non-existent port (for testing auth only)
		Hostname:      "auth.localhost",
		BasicAuth: &config.BasicAuth{
			User:  "admin",
			Pass:  "secret",
			Realm: "Admin Area",
		},
	}
	router.AddBackend(backend)

	tests := []struct {
		name         string
		user         string
		pass         string
		expectStatus int
	}{
		{
			name:         "no credentials",
			user:         "",
			pass:         "",
			expectStatus: http.StatusUnauthorized,
		},
		{
			name:         "wrong credentials",
			user:         "wrong",
			pass:         "wrong",
			expectStatus: http.StatusUnauthorized,
		},
		{
			name:         "correct credentials (backend unavailable)",
			user:         "admin",
			pass:         "secret",
			expectStatus: http.StatusBadGateway, // Auth passes, but backend is unavailable
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			req := httptest.NewRequest("GET", "https://auth.localhost/", nil)
			req.Host = "auth.localhost"
			if tt.user != "" || tt.pass != "" {
				req.SetBasicAuth(tt.user, tt.pass)
			}
			w := httptest.NewRecorder()

			handler.ServeHTTP(w, req)

			if w.Code != tt.expectStatus {
				t.Errorf("status = %d, want %d", w.Code, tt.expectStatus)
			}

			if tt.expectStatus == http.StatusUnauthorized {
				if header := w.Header().Get("WWW-Authenticate"); header != `Basic realm="Admin Area"` {
					t.Errorf("WWW-Authenticate = %q, want %q", header, `Basic realm="Admin Area"`)
				}
			}
		})
	}
}

func TestHandler_ProjectOperation_MethodNotAllowed(t *testing.T) {
	router := NewRouter()
	store := project.NewStore("")
	store.Update(&project.Project{
		Name:       "myapp",
		WorkingDir: "/tmp/myapp",
		Active:     true,
	})
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), store)

	tests := []struct {
		name           string
		path           string
		method         string
		expectedStatus int
	}{
		// up/down/restart require POST
		{"up with GET", "/_api/projects/myapp/up", "GET", http.StatusMethodNotAllowed},
		{"down with GET", "/_api/projects/myapp/down", "GET", http.StatusMethodNotAllowed},
		{"restart with GET", "/_api/projects/myapp/restart", "GET", http.StatusMethodNotAllowed},
		// logs requires GET
		{"logs with POST", "/_api/projects/myapp/logs", "POST", http.StatusMethodNotAllowed},
		// delete requires DELETE
		{"delete with POST", "/_api/projects/myapp/delete", "POST", http.StatusMethodNotAllowed},
		{"delete with GET", "/_api/projects/myapp/delete", "GET", http.StatusMethodNotAllowed},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			req := httptest.NewRequest(tt.method, "https://roji.dev.localhost"+tt.path, nil)
			req.Host = "roji.dev.localhost"
			w := httptest.NewRecorder()

			handler.ServeHTTP(w, req)

			if w.Code != tt.expectedStatus {
				t.Errorf("status = %d, want %d", w.Code, tt.expectedStatus)
			}
		})
	}
}

func TestHandler_ProjectOperation_ProjectNotFound(t *testing.T) {
	router := NewRouter()
	store := project.NewStore("")
	// Handler has project store but no docker client — however, docker client
	// is checked before project lookup. To test "not found", we need the docker
	// client nil check to pass. Since getProjectOrError checks projectStore first,
	// then dockerClient, then project name, we test with nil dockerClient which
	// returns 503. To truly test 404, we need non-nil dockerClient, but we can't
	// easily create one in tests. Instead, test the 503 path for nil docker client
	// is already covered. Here we check that an unknown project name with nil
	// docker client returns 503 (service unavailable).
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), store)

	req := httptest.NewRequest("POST", "https://roji.dev.localhost/_api/projects/nonexistent/up", nil)
	req.Host = "roji.dev.localhost"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	// With nil docker client, returns 503 before checking project existence
	if w.Code != http.StatusServiceUnavailable {
		t.Errorf("status = %d, want %d", w.Code, http.StatusServiceUnavailable)
	}
}

func TestHandler_ProjectOperation_NilProjectStore(t *testing.T) {
	router := NewRouter()
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	req := httptest.NewRequest("POST", "https://roji.dev.localhost/_api/projects/myapp/up", nil)
	req.Host = "roji.dev.localhost"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	if w.Code != http.StatusServiceUnavailable {
		t.Errorf("status = %d, want %d", w.Code, http.StatusServiceUnavailable)
	}
}

func TestHandler_ProjectOperation_InvalidName(t *testing.T) {
	router := NewRouter()
	store := project.NewStore("")
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), store)

	// Test with names that are invalid but don't break URL parsing
	tests := []struct {
		name string
		path string
	}{
		{"path traversal", "/_api/projects/my;rm/up"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			req := httptest.NewRequest("POST", "https://roji.dev.localhost"+tt.path, nil)
			req.Host = "roji.dev.localhost"
			w := httptest.NewRecorder()

			handler.ServeHTTP(w, req)

			if w.Code != http.StatusBadRequest {
				t.Errorf("path %q: status = %d, want %d", tt.path, w.Code, http.StatusBadRequest)
			}
		})
	}
}

func TestHandler_ProjectOperation_RouteDispatch(t *testing.T) {
	router := NewRouter()
	store := project.NewStore("")
	store.Update(&project.Project{
		Name:       "my-app",
		WorkingDir: "/tmp/myapp",
		Active:     true,
	})
	store.Update(&project.Project{
		Name:       "my.project",
		WorkingDir: "/tmp/myproject",
		Active:     true,
	})
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), store)

	tests := []struct {
		name           string
		path           string
		expectedStatus int
	}{
		// Valid project names with hyphens and dots
		{"hyphenated name", "/_api/projects/my-app/up", http.StatusServiceUnavailable}, // no docker client
		{"dotted name", "/_api/projects/my.project/up", http.StatusServiceUnavailable}, // no docker client
		// Invalid paths
		{"no action", "/_api/projects/myapp/", http.StatusBadRequest},
		{"unknown action", "/_api/projects/myapp/unknown", http.StatusBadRequest},
		{"missing name", "/_api/projects//up", http.StatusBadRequest},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			req := httptest.NewRequest("POST", "https://roji.dev.localhost"+tt.path, nil)
			req.Host = "roji.dev.localhost"
			w := httptest.NewRecorder()

			handler.ServeHTTP(w, req)

			if w.Code != tt.expectedStatus {
				t.Errorf("path %q: status = %d, want %d", tt.path, w.Code, tt.expectedStatus)
			}
		})
	}
}

func TestHandler_ProjectOperation_CORS(t *testing.T) {
	router := NewRouter()
	store := project.NewStore("")
	store.Update(&project.Project{
		Name:       "myapp",
		WorkingDir: "/tmp/myapp",
		Active:     false,
	})
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), store)

	t.Run("preflight OPTIONS returns CORS headers", func(t *testing.T) {
		req := httptest.NewRequest("OPTIONS", "https://roji.dev.localhost/_api/projects/myapp/up", nil)
		req.Host = "roji.dev.localhost"
		req.Header.Set("Origin", "https://myapp.dev.localhost")
		w := httptest.NewRecorder()

		handler.ServeHTTP(w, req)

		if w.Code != http.StatusNoContent {
			t.Errorf("status = %d, want %d", w.Code, http.StatusNoContent)
		}
		if got := w.Header().Get("Access-Control-Allow-Origin"); got != "https://myapp.dev.localhost" {
			t.Errorf("Access-Control-Allow-Origin = %q, want %q", got, "https://myapp.dev.localhost")
		}
		if got := w.Header().Get("Access-Control-Allow-Methods"); got == "" {
			t.Error("Access-Control-Allow-Methods should be set")
		}
	})

	t.Run("no CORS for non-subdomain origin", func(t *testing.T) {
		req := httptest.NewRequest("OPTIONS", "https://roji.dev.localhost/_api/projects/myapp/up", nil)
		req.Host = "roji.dev.localhost"
		req.Header.Set("Origin", "https://evil.example.com")
		w := httptest.NewRecorder()

		handler.ServeHTTP(w, req)

		if got := w.Header().Get("Access-Control-Allow-Origin"); got != "" {
			t.Errorf("Access-Control-Allow-Origin should be empty for external origin, got %q", got)
		}
	})

	t.Run("no CORS without Origin header", func(t *testing.T) {
		req := httptest.NewRequest("OPTIONS", "https://roji.dev.localhost/_api/projects/myapp/up", nil)
		req.Host = "roji.dev.localhost"
		w := httptest.NewRecorder()

		handler.ServeHTTP(w, req)

		if got := w.Header().Get("Access-Control-Allow-Origin"); got != "" {
			t.Errorf("Access-Control-Allow-Origin should be empty without Origin, got %q", got)
		}
	})
}

func TestIsValidProjectName(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  bool
	}{
		{"simple", "myapp", true},
		{"with hyphen", "my-app", true},
		{"with dot", "my.app", true},
		{"with underscore", "my_app", true},
		{"with numbers", "app123", true},
		{"all allowed chars", "my-app_v1.2", true},
		{"empty", "", false},
		{"with space", "my app", false},
		{"with semicolon", "my;app", false},
		{"with slash", "my/app", false},
		{"shell injection", "$(whoami)", false},
		{"dots only", "..", true}, // dots are valid; name is only used as store key, not file path
		{"backticks", "`id`", false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := isValidProjectName(tt.input)
			if got != tt.want {
				t.Errorf("isValidProjectName(%q) = %v, want %v", tt.input, got, tt.want)
			}
		})
	}
}

func TestHandler_ProjectDelete(t *testing.T) {
	t.Run("successful delete", func(t *testing.T) {
		router := NewRouter()
		store := project.NewStore("")
		store.Update(&project.Project{
			Name:       "old-project",
			WorkingDir: "/tmp/old",
			Active:     false,
		})
		handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), store)

		req := httptest.NewRequest("DELETE", "https://roji.dev.localhost/_api/projects/old-project/delete", nil)
		req.Host = "roji.dev.localhost"
		w := httptest.NewRecorder()

		handler.ServeHTTP(w, req)

		if w.Code != http.StatusOK {
			t.Errorf("status = %d, want %d", w.Code, http.StatusOK)
		}

		// Verify project was removed from store
		if p := store.Get("old-project"); p != nil {
			t.Error("project should have been removed from store")
		}
	})

	t.Run("method not allowed - POST", func(t *testing.T) {
		router := NewRouter()
		store := project.NewStore("")
		store.Update(&project.Project{
			Name:       "myapp",
			WorkingDir: "/tmp/myapp",
			Active:     false,
		})
		handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), store)

		req := httptest.NewRequest("POST", "https://roji.dev.localhost/_api/projects/myapp/delete", nil)
		req.Host = "roji.dev.localhost"
		w := httptest.NewRecorder()

		handler.ServeHTTP(w, req)

		if w.Code != http.StatusMethodNotAllowed {
			t.Errorf("status = %d, want %d", w.Code, http.StatusMethodNotAllowed)
		}
	})

	t.Run("project not found", func(t *testing.T) {
		router := NewRouter()
		store := project.NewStore("")
		handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), store)

		req := httptest.NewRequest("DELETE", "https://roji.dev.localhost/_api/projects/nonexistent/delete", nil)
		req.Host = "roji.dev.localhost"
		w := httptest.NewRecorder()

		handler.ServeHTTP(w, req)

		if w.Code != http.StatusNotFound {
			t.Errorf("status = %d, want %d", w.Code, http.StatusNotFound)
		}
	})

	t.Run("CORS allows DELETE method", func(t *testing.T) {
		router := NewRouter()
		store := project.NewStore("")
		store.Update(&project.Project{
			Name:       "myapp",
			WorkingDir: "/tmp/myapp",
			Active:     false,
		})
		handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), store)

		req := httptest.NewRequest("OPTIONS", "https://roji.dev.localhost/_api/projects/myapp/delete", nil)
		req.Host = "roji.dev.localhost"
		req.Header.Set("Origin", "https://myapp.dev.localhost")
		w := httptest.NewRecorder()

		handler.ServeHTTP(w, req)

		if w.Code != http.StatusNoContent {
			t.Errorf("status = %d, want %d", w.Code, http.StatusNoContent)
		}
		methods := w.Header().Get("Access-Control-Allow-Methods")
		if !strings.Contains(methods, "DELETE") {
			t.Errorf("Access-Control-Allow-Methods = %q, should contain DELETE", methods)
		}
	})
}

func TestHandler_NotFound_WithInactiveProject(t *testing.T) {
	router := NewRouter()
	store := project.NewStore("")

	// Add an inactive project
	store.Update(&project.Project{
		Name:       "myapp",
		WorkingDir: "/home/user/myapp",
		Active:     false,
		Services:   []string{"web", "db"},
	})

	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), store)

	// Access hostname that matches inactive project
	req := httptest.NewRequest("GET", "https://myapp.dev.localhost/", nil)
	req.Host = "myapp.dev.localhost"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	if w.Code != http.StatusNotFound {
		t.Errorf("status = %d, want %d", w.Code, http.StatusNotFound)
	}

	body := w.Body.String()
	if !strings.Contains(body, "myapp") {
		t.Errorf("body should contain project name 'myapp'")
	}
	if !strings.Contains(body, "Start") {
		t.Errorf("body should contain 'Start' button")
	}
	if !strings.Contains(body, "/_api/projects/myapp/up") {
		t.Errorf("body should contain start API URL")
	}
}

func TestHandler_NotFound_WithMultiServiceProject(t *testing.T) {
	router := NewRouter()
	store := project.NewStore("")

	store.Update(&project.Project{
		Name:       "myapp",
		WorkingDir: "/home/user/myapp",
		Active:     false,
		Services:   []string{"web", "api"},
	})

	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), store)

	// Access "web-myapp.dev.localhost" — multi-service pattern
	req := httptest.NewRequest("GET", "https://web-myapp.dev.localhost/", nil)
	req.Host = "web-myapp.dev.localhost"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	if w.Code != http.StatusNotFound {
		t.Errorf("status = %d, want %d", w.Code, http.StatusNotFound)
	}

	body := w.Body.String()
	if !strings.Contains(body, "myapp") {
		t.Errorf("body should contain project name 'myapp'")
	}
	if !strings.Contains(body, "Start") {
		t.Errorf("body should contain 'Start' button for multi-service hostname match")
	}
}

func TestHandler_NotFound_NoMatchForActiveProject(t *testing.T) {
	router := NewRouter()
	store := project.NewStore("")

	// Add an active project — should NOT show start button
	store.Update(&project.Project{
		Name:       "myapp",
		WorkingDir: "/home/user/myapp",
		Active:     true,
		Services:   []string{"web"},
	})

	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), store)

	req := httptest.NewRequest("GET", "https://myapp.dev.localhost/", nil)
	req.Host = "myapp.dev.localhost"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	body := w.Body.String()
	if strings.Contains(body, "project-start\">") {
		t.Errorf("body should NOT contain project-start section for active project")
	}
}

func TestHandler_NotFound_NoMatchForUnknownHost(t *testing.T) {
	router := NewRouter()
	store := project.NewStore("")

	store.Update(&project.Project{
		Name:       "myapp",
		WorkingDir: "/home/user/myapp",
		Active:     false,
	})

	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), store)

	// Access unrelated hostname — should NOT show start button
	req := httptest.NewRequest("GET", "https://other.dev.localhost/", nil)
	req.Host = "other.dev.localhost"
	w := httptest.NewRecorder()

	handler.ServeHTTP(w, req)

	body := w.Body.String()
	if strings.Contains(body, "project-start\">") {
		t.Errorf("body should NOT contain project-start section for unmatched hostname")
	}
}

func TestClientIP(t *testing.T) {
	tests := []struct {
		name       string
		remoteAddr string
		want       string
	}{
		{"IPv6 loopback", "[::1]:54321", "::1"},
		{"IPv6 address", "[2001:db8::17]:443", "2001:db8::17"},
		{"IPv6 zone", "[fe80::1%eth0]:8080", "fe80::1%eth0"},
		{"IPv4", "127.0.0.1:54321", "127.0.0.1"},
		{"empty", "", ""},
		{"no port", "127.0.0.1", ""},
		{"malformed", "not-an-address", ""},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := clientIP(tt.remoteAddr); got != tt.want {
				t.Errorf("clientIP(%q) = %q, want %q", tt.remoteAddr, got, tt.want)
			}
		})
	}
}

func TestHostWithoutPort(t *testing.T) {
	tests := []struct {
		name string
		host string
		want string
	}{
		{"hostname with port", "api.localhost:8443", "api.localhost"},
		{"hostname without port", "api.localhost", "api.localhost"},
		{"IPv6 with port", "[::1]:443", "::1"},
		{"IPv6 without port", "[::1]", "::1"},
		{"IPv4 with port", "127.0.0.1:8443", "127.0.0.1"},
		{"empty", "", ""},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := hostWithoutPort(tt.host); got != tt.want {
				t.Errorf("hostWithoutPort(%q) = %q, want %q", tt.host, got, tt.want)
			}
		})
	}
}

func TestHostForURL(t *testing.T) {
	tests := []struct {
		name string
		host string
		want string
	}{
		{"hostname", "api.localhost", "api.localhost"},
		{"IPv4", "127.0.0.1", "127.0.0.1"},
		{"IPv6", "::1", "[::1]"},
		{"empty", "", ""},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := hostForURL(tt.host); got != tt.want {
				t.Errorf("hostForURL(%q) = %q, want %q", tt.host, got, tt.want)
			}
		})
	}
}

// addBackendFor registers a route pointing at the given test server URL,
// optionally under a path prefix.
func addBackendFor(t *testing.T, router *Router, hostname, serverURL string, pathPrefix ...string) {
	t.Helper()

	u, err := url.Parse(serverURL)
	if err != nil {
		t.Fatalf("parse backend URL: %v", err)
	}
	port, err := strconv.Atoi(u.Port())
	if err != nil {
		t.Fatalf("parse backend port: %v", err)
	}

	backend := &docker.Backend{
		ContainerID:   hostname,
		ContainerName: hostname,
		ServiceName:   hostname,
		Host:          u.Hostname(),
		Port:          port,
		Hostname:      hostname,
	}
	if len(pathPrefix) > 0 {
		backend.PathPrefix = pathPrefix[0]
	}
	router.AddBackend(backend)
}

// recordedRequest is what a backend received. The zero value stands for
// "no request arrived"; header.Get reads fine from a nil Header.
type recordedRequest struct {
	header http.Header
	host   string
	path   string
	// requestURI is the request line as sent, so it shows the encoding the
	// decoded path cannot: "/files/a%2Fb" against "/files/a/b".
	requestURI string
	rawQuery   string
}

// forwardedRecorder captures what a backend receives.
type forwardedRecorder struct {
	mu   sync.Mutex
	last recordedRequest
}

func (fr *forwardedRecorder) record(r *http.Request) {
	fr.mu.Lock()
	defer fr.mu.Unlock()
	fr.last = recordedRequest{
		header:     r.Header.Clone(),
		host:       r.Host,
		path:       r.URL.Path,
		requestURI: r.RequestURI,
		rawQuery:   r.URL.RawQuery,
	}
}

// get returns the last request the backend received.
func (fr *forwardedRecorder) get() recordedRequest {
	fr.mu.Lock()
	defer fr.mu.Unlock()
	return fr.last
}

// reset clears the recorder so a subtest cannot read values left by the
// previous one when a request never reaches the backend.
func (fr *forwardedRecorder) reset() {
	fr.mu.Lock()
	defer fr.mu.Unlock()
	fr.last = recordedRequest{}
}

func TestHandler_ForwardedHeaders_HTTP(t *testing.T) {
	rec := &forwardedRecorder{}
	backendServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		rec.record(r)
	}))
	defer backendServer.Close()

	router := NewRouter()
	addBackendFor(t, router, "xff.localhost", backendServer.URL)
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	tests := []struct {
		name             string
		remoteAddr       string
		spoofedForwarded string
		wantForwardedFor string
		wantRealIP       string
	}{
		{
			name:             "IPv6 client has no brackets",
			remoteAddr:       "[::1]:54321",
			wantForwardedFor: "::1",
			wantRealIP:       "::1",
		},
		{
			name:             "IPv6 global address",
			remoteAddr:       "[2001:db8::17]:443",
			wantForwardedFor: "2001:db8::17",
			wantRealIP:       "2001:db8::17",
		},
		{
			name:             "IPv4 client is forwarded once",
			remoteAddr:       "127.0.0.1:54321",
			wantForwardedFor: "127.0.0.1",
			wantRealIP:       "127.0.0.1",
		},
		{
			name:             "spoofed headers are replaced",
			remoteAddr:       "[::1]:54321",
			spoofedForwarded: "10.0.0.99",
			wantForwardedFor: "::1",
			wantRealIP:       "::1",
		},
		{
			name:             "malformed RemoteAddr is skipped",
			remoteAddr:       "not-an-address",
			wantForwardedFor: "",
			wantRealIP:       "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			rec.reset()

			req := httptest.NewRequest("GET", "https://xff.localhost/", nil)
			req.Host = "xff.localhost"
			req.RemoteAddr = tt.remoteAddr
			if tt.spoofedForwarded != "" {
				req.Header.Set("X-Forwarded-For", tt.spoofedForwarded)
				req.Header.Set("X-Real-IP", tt.spoofedForwarded)
				// RFC 7239 equivalent, which roji never emits itself
				req.Header.Set("Forwarded", "for="+tt.spoofedForwarded+";host=evil.example;proto=http")
			}

			handler.ServeHTTP(httptest.NewRecorder(), req)

			got := rec.get()
			if v := got.header.Get("X-Forwarded-For"); v != tt.wantForwardedFor {
				t.Errorf("X-Forwarded-For = %q, want %q", v, tt.wantForwardedFor)
			}
			if v := got.header.Get("X-Real-IP"); v != tt.wantRealIP {
				t.Errorf("X-Real-IP = %q, want %q", v, tt.wantRealIP)
			}
			if v := got.header.Get("Forwarded"); v != "" {
				t.Errorf("Forwarded = %q, want it dropped", v)
			}
		})
	}
}

func TestHandler_ForwardedHeaders_GRPC(t *testing.T) {
	rec := &forwardedRecorder{}
	backendServer := httptest.NewUnstartedServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		rec.record(r)
		w.Header().Set("Content-Type", "application/grpc")
	}))
	// gRPC backends speak HTTP/2; serve unencrypted HTTP/2 so the proxy's
	// HTTP/2 transport connects.
	backendServer.Config.Protocols = new(http.Protocols)
	backendServer.Config.Protocols.SetUnencryptedHTTP2(true)
	backendServer.Start()
	defer backendServer.Close()

	router := NewRouter()
	addBackendFor(t, router, "grpc-xff.localhost", backendServer.URL)
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	tests := []struct {
		name       string
		remoteAddr string
		want       string
	}{
		{"IPv6 client has no brackets", "[::1]:54321", "::1"},
		{"IPv4 client is forwarded once", "127.0.0.1:54321", "127.0.0.1"},
		{"malformed RemoteAddr is skipped", "not-an-address", ""},
	}
	// X-Real-IP carries the same value on every protocol path.

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			rec.reset()

			req := httptest.NewRequest("POST", "https://grpc-xff.localhost/chat.ChatService/GetUsers", nil)
			req.Host = "grpc-xff.localhost"
			req.Header.Set("Content-Type", "application/grpc")
			req.Header.Set("TE", "trailers")
			req.RemoteAddr = tt.remoteAddr

			w := httptest.NewRecorder()
			handler.ServeHTTP(w, req)

			if w.Code != http.StatusOK {
				t.Fatalf("status = %d, want %d", w.Code, http.StatusOK)
			}
			got := rec.get()
			if v := got.header.Get("X-Forwarded-For"); v != tt.want {
				t.Errorf("X-Forwarded-For = %q, want %q", v, tt.want)
			}
			if v := got.header.Get("X-Real-IP"); v != tt.want {
				t.Errorf("X-Real-IP = %q, want %q", v, tt.want)
			}
		})
	}
}

func TestHandler_ForwardedHeaders_WebSocket(t *testing.T) {
	rec := &forwardedRecorder{}
	backendServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		rec.record(r)
		upgrader := websocket.Upgrader{
			CheckOrigin: func(r *http.Request) bool { return true },
		}
		conn, err := upgrader.Upgrade(w, r, nil)
		if err != nil {
			t.Logf("backend upgrade error: %v", err)
			return
		}
		conn.Close()
	}))
	defer backendServer.Close()

	router := NewRouter()
	addBackendFor(t, router, "ws-xff.localhost", backendServer.URL)
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	// The websocket path needs a hijackable connection, so RemoteAddr comes from
	// a real client. Listen on IPv6 loopback to exercise the bracketed form.
	listener, err := net.Listen("tcp", "[::1]:0")
	if err != nil {
		t.Skipf("IPv6 loopback unavailable: %v", err)
	}
	proxyServer := httptest.NewUnstartedServer(handler)
	proxyServer.Listener.Close()
	proxyServer.Listener = listener
	proxyServer.Start()
	defer proxyServer.Close()

	header := http.Header{}
	header.Set("Host", "ws-xff.localhost")
	conn, _, err := websocket.DefaultDialer.Dial("ws://"+listener.Addr().String()+"/ws", header)
	if err != nil {
		t.Fatalf("WebSocket dial failed: %v", err)
	}
	defer conn.Close()

	got := rec.get()
	if v := got.header.Get("X-Forwarded-For"); v != "::1" {
		t.Errorf("X-Forwarded-For = %q, want %q", v, "::1")
	}
	if v := got.header.Get("X-Real-IP"); v != "::1" {
		t.Errorf("X-Real-IP = %q, want %q", v, "::1")
	}
}

// TestHandler_ProxiedRequest_HTTP covers what the Rewrite hook has to get
// right beyond the client IP: the Host the backend is addressed with, the
// forwarded scheme, and path prefix stripping.
func TestHandler_ProxiedRequest_HTTP(t *testing.T) {
	rec := &forwardedRecorder{}
	backendServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		rec.record(r)
	}))
	defer backendServer.Close()

	router := NewRouter()
	addBackendFor(t, router, "proxied.localhost", backendServer.URL, "/api")
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	req := httptest.NewRequest("GET", "https://proxied.localhost/api/users", nil)
	req.Host = "proxied.localhost"
	req.RemoteAddr = "127.0.0.1:54321"
	handler.ServeHTTP(httptest.NewRecorder(), req)

	got := rec.get()
	// The client's hostname reaches the backend, not the backend's own address:
	// dev servers key on it for virtual hosts and host allowlists.
	if got.host != "proxied.localhost" {
		t.Errorf("Host = %q, want %q", got.host, "proxied.localhost")
	}
	if got.path != "/users" {
		t.Errorf("path = %q, want %q (prefix stripped)", got.path, "/users")
	}
	if v := got.header.Get("X-Forwarded-Host"); v != "proxied.localhost" {
		t.Errorf("X-Forwarded-Host = %q, want %q", v, "proxied.localhost")
	}
	// roji terminates TLS in front of the backend, so the scheme is https even
	// though this test drives the handler over a plain connection.
	if v := got.header.Get("X-Forwarded-Proto"); v != "https" {
		t.Errorf("X-Forwarded-Proto = %q, want %q", v, "https")
	}
}

// TestHandler_ProxiedRequest_GRPC checks the gRPC path addresses the backend
// by its own host, which is what the :authority pseudo-header has to carry.
func TestHandler_ProxiedRequest_GRPC(t *testing.T) {
	rec := &forwardedRecorder{}
	backendServer := httptest.NewUnstartedServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		rec.record(r)
		w.Header().Set("Content-Type", "application/grpc")
	}))
	backendServer.Config.Protocols = new(http.Protocols)
	backendServer.Config.Protocols.SetUnencryptedHTTP2(true)
	backendServer.Start()
	defer backendServer.Close()

	router := NewRouter()
	addBackendFor(t, router, "grpc-host.localhost", backendServer.URL)
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	backendURL, err := url.Parse(backendServer.URL)
	if err != nil {
		t.Fatalf("parse backend URL: %v", err)
	}

	req := httptest.NewRequest("POST", "https://grpc-host.localhost/chat.ChatService/GetUsers?q=50%&page=2", nil)
	req.Host = "grpc-host.localhost"
	req.Header.Set("Content-Type", "application/grpc")
	req.Header.Set("TE", "trailers")
	req.RemoteAddr = "127.0.0.1:54321"

	w := httptest.NewRecorder()
	handler.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d", w.Code, http.StatusOK)
	}
	got := rec.get()
	if got.host != backendURL.Host {
		t.Errorf("Host = %q, want %q", got.host, backendURL.Host)
	}
	// The path carries the gRPC service and method the backend routes on, so
	// it has to arrive byte for byte.
	if got.path != "/chat.ChatService/GetUsers" {
		t.Errorf("path = %q, want %q", got.path, "/chat.ChatService/GetUsers")
	}
	if v := got.header.Get("X-Forwarded-Host"); v != "grpc-host.localhost" {
		t.Errorf("X-Forwarded-Host = %q, want %q", v, "grpc-host.localhost")
	}
	if v := got.header.Get("X-Forwarded-Proto"); v != "https" {
		t.Errorf("X-Forwarded-Proto = %q, want %q", v, "https")
	}
	// The query has to survive this path too, not just the HTTP one
	if got.rawQuery != "q=50%&page=2" {
		t.Errorf("RawQuery = %q, want %q (forwarded verbatim)", got.rawQuery, "q=50%&page=2")
	}
}

// TestHandler_ProxiedRequest_PreservesRawQuery guards against the query
// mangling httputil.ReverseProxy applies on the Rewrite path: it drops
// parameters it cannot parse before the rewrite hook runs.
func TestHandler_ProxiedRequest_PreservesRawQuery(t *testing.T) {
	rec := &forwardedRecorder{}
	backendServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		rec.record(r)
	}))
	defer backendServer.Close()

	router := NewRouter()
	addBackendFor(t, router, "query.localhost", backendServer.URL)
	handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

	tests := []struct {
		name     string
		rawQuery string
	}{
		{"ordinary query", "name=foo&x=1"},
		{"bare percent sign", "q=50%&page=2"},
		{"semicolon separator", "a=1;b=2"},
		{"empty", ""},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			rec.reset()

			req := httptest.NewRequest("GET", "https://query.localhost/search", nil)
			req.URL.RawQuery = tt.rawQuery
			req.Host = "query.localhost"
			req.RemoteAddr = "127.0.0.1:54321"

			handler.ServeHTTP(httptest.NewRecorder(), req)

			if got := rec.get().rawQuery; got != tt.rawQuery {
				t.Errorf("RawQuery = %q, want %q (forwarded verbatim)", got, tt.rawQuery)
			}
		})
	}
}

// TestHandler_ProxiedRequest_PreservesEncodedPath checks that stripping a route's
// path prefix does not re-escape the rest of the path. A stale RawPath makes
// url.EscapedPath fall back to escaping Path, which decodes "%2F" into a real
// separator and turns one path segment into two.
func TestHandler_ProxiedRequest_PreservesEncodedPath(t *testing.T) {
	rec := &forwardedRecorder{}
	backendServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		rec.record(r)
	}))
	defer backendServer.Close()

	tests := []struct {
		name       string
		pathPrefix []string
		requestURL string
		want       string
	}{
		{"with prefix", []string{"/api"}, "https://enc.localhost/api/files/a%2Fb", "/files/a%2Fb"},
		{"without prefix", nil, "https://enc.localhost/files/a%2Fb", "/files/a%2Fb"},
		{"prefix is the whole path", []string{"/api"}, "https://enc.localhost/api", "/"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			rec.reset()

			router := NewRouter()
			addBackendFor(t, router, "enc.localhost", backendServer.URL, tt.pathPrefix...)
			handler := NewHandler(router, nil, "roji.dev.localhost", "dev.localhost", testStatusConfig(), nil)

			req := httptest.NewRequest("GET", tt.requestURL, nil)
			req.Host = "enc.localhost"
			req.RemoteAddr = "127.0.0.1:54321"
			handler.ServeHTTP(httptest.NewRecorder(), req)

			if got := rec.get().requestURI; got != tt.want {
				t.Errorf("backend RequestURI = %q, want %q", got, tt.want)
			}
		})
	}
}
