// Package proxy provides HTTP/HTTPS reverse proxy functionality.
//
// It handles:
//   - Dynamic routing based on hostname and path
//   - TLS termination with auto-generated certificates
//   - Real-time dashboard with Server-Sent Events (SSE)
//   - Health check and status endpoints
package proxy

import (
	"context"
	"crypto/tls"
	"embed"
	"encoding/json"
	"fmt"
	"html/template"
	"log/slog"
	"net"
	"net/http"
	"net/http/httputil"
	"net/url"
	"strings"
	"time"

	"github.com/gorilla/websocket"
	"github.com/kan/roji/config"
	"github.com/kan/roji/docker"
	"github.com/kan/roji/project"
	"golang.org/x/net/http2"
)

// sharedTransport is used for connection pooling across all proxied requests (HTTP/1.1)
var sharedTransport = &http.Transport{
	MaxIdleConns:        100,
	MaxIdleConnsPerHost: 10,
	IdleConnTimeout:     90 * time.Second,
}

// http2Transport is used for gRPC proxying (HTTP/2)
var http2Transport = &http2.Transport{
	AllowHTTP: true, // Allow h2c (HTTP/2 without TLS) for backend connections
	DialTLSContext: func(ctx context.Context, network, addr string, cfg *tls.Config) (net.Conn, error) {
		// Use plain TCP for backend connections (h2c)
		return net.Dial(network, addr)
	},
}

// isGRPCRequest checks if the request is a gRPC request
func isGRPCRequest(r *http.Request) bool {
	contentType := r.Header.Get("Content-Type")
	return strings.HasPrefix(contentType, "application/grpc")
}

// wsUpgrader is used to upgrade HTTP connections to WebSocket
var wsUpgrader = websocket.Upgrader{
	ReadBufferSize:  1024,
	WriteBufferSize: 1024,
	CheckOrigin: func(r *http.Request) bool {
		return true // Allow all origins for local development
	},
}

// isWebSocketRequest checks if the request is a WebSocket upgrade request
func isWebSocketRequest(r *http.Request) bool {
	return strings.EqualFold(r.Header.Get("Upgrade"), "websocket") &&
		strings.Contains(strings.ToLower(r.Header.Get("Connection")), "upgrade")
}

//go:embed templates/*.html templates/*.js templates/*.svg templates/*.css
var templateFS embed.FS

var templates = template.Must(
	template.New("").Delims("[[", "]]").ParseFS(templateFS, "templates/*.html"),
)

// StatusConfig contains configuration for the status endpoint
type StatusConfig struct {
	Version       string
	Commit        string
	Date          string
	BuiltBy       string
	StartTime     time.Time
	CertsDir      string
	AutoGenerated bool
	Networks      []string // Docker networks being watched
	BaseDomain    string
	HTTPPort      int
	HTTPSPort     int
}

// Handler is the main HTTP handler for the reverse proxy
type Handler struct {
	router        *Router
	dockerClient  *docker.Client
	logBuffer     *LogBuffer
	dashboardHost string // hostname for dashboard (e.g., "roji.dev.localhost")
	baseDomain    string // base domain (e.g., "dev.localhost")
	statusConfig  *StatusConfig
	projectStore  *project.Store
}

// NewHandler creates a new proxy handler
func NewHandler(router *Router, dockerClient *docker.Client, dashboardHost string, baseDomain string, statusConfig *StatusConfig, projectStore *project.Store) *Handler {
	return &Handler{
		router:        router,
		dockerClient:  dockerClient,
		logBuffer:     NewLogBuffer(100), // Keep last 100 requests
		dashboardHost: strings.ToLower(dashboardHost),
		baseDomain:    strings.ToLower(baseDomain),
		statusConfig:  statusConfig,
		projectStore:  projectStore,
	}
}

// ServeHTTP implements http.Handler
func (h *Handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	startTime := time.Now()

	// Extract hostname (remove port if present)
	hostname := r.Host
	if idx := strings.LastIndex(hostname, ":"); idx != -1 {
		hostname = hostname[:idx]
	}
	hostname = strings.ToLower(hostname)

	// Check if this is a dashboard-related host
	isDashboardHost := h.dashboardHost != "" && hostname == h.dashboardHost
	isBaseDomain := h.baseDomain != "" && hostname == h.baseDomain

	if isDashboardHost || isBaseDomain {
		// If accessing via base domain, redirect to dashboard host
		if isBaseDomain && !isDashboardHost {
			// Construct redirect URL
			scheme := "https"
			redirectURL := fmt.Sprintf("%s://%s%s", scheme, h.dashboardHost, r.URL.RequestURI())
			http.Redirect(w, r, redirectURL, http.StatusFound) // 302 Temporary Redirect
			return
		}

		// Health check endpoints
		if r.URL.Path == "/_api/health" || r.URL.Path == "/healthz" {
			h.serveHealth(w, r)
			return
		}
		// Status endpoint
		if r.URL.Path == "/_api/status" {
			h.serveStatus(w, r)
			return
		}
		// API endpoint for route listing
		if r.URL.Path == "/_api/routes" {
			h.serveRoutesAPI(w, r)
			return
		}
		// API endpoint for project listing
		if r.URL.Path == "/_api/projects" {
			h.serveProjectsAPI(w, r)
			return
		}
		// SSE endpoint for real-time route updates
		if r.URL.Path == "/_api/events" {
			h.serveSSE(w, r)
			return
		}
		// Container restart endpoint
		if strings.HasPrefix(r.URL.Path, "/_api/containers/") && strings.HasSuffix(r.URL.Path, "/restart") {
			h.serveContainerRestart(w, r)
			return
		}
		// Request logs endpoint
		if r.URL.Path == "/_api/logs" {
			h.serveLogsAPI(w, r)
			return
		}
		// SSE endpoint for real-time log updates
		if r.URL.Path == "/_api/logs/events" {
			h.serveLogsSSE(w, r)
			return
		}
		// Static assets (petite-vue.min.js, etc.)
		if strings.HasPrefix(r.URL.Path, "/_assets/") {
			h.serveAsset(w, r)
			return
		}
		h.serveDashboard(w, r)
		return
	}

	// Look up route
	route := h.router.Lookup(hostname, r.URL.Path)
	if route == nil {
		h.handleNotFound(w, r, hostname)
		return
	}

	// Check if this request matches a mock route (before warning check,
	// since mocks can work without a real backend)
	if mock := h.findMockRoute(route, r.Method, r.URL.Path); mock != nil {
		h.serveMockResponse(w, r, mock, hostname, route)
		return
	}

	// Check if route has a warning (e.g., no port exposed)
	if route.Backend.Warning != "" {
		h.handleRouteWarning(w, r, hostname, route)
		return
	}

	// Create target URL for backend
	targetURL := &url.URL{
		Scheme: "http",
		Host:   fmt.Sprintf("%s:%d", route.Backend.Host, route.Backend.Port),
	}

	// Handle WebSocket upgrade requests
	if isWebSocketRequest(r) {
		h.serveWebSocket(w, r, targetURL, route, hostname, startTime)
		return
	}

	// Handle gRPC requests (HTTP/2)
	if isGRPCRequest(r) {
		h.serveGRPC(w, r, targetURL, route, hostname, startTime)
		return
	}

	// Create reverse proxy for this request
	proxy := httputil.NewSingleHostReverseProxy(targetURL)

	// Use shared transport for connection pooling
	proxy.Transport = sharedTransport

	// SSE support: flush responses immediately (disable buffering)
	proxy.FlushInterval = -1

	// Customize the director to handle path prefixes
	originalDirector := proxy.Director
	proxy.Director = func(req *http.Request) {
		originalDirector(req)

		// Strip path prefix if configured
		if route.PathPrefix != "" {
			req.URL.Path = strings.TrimPrefix(req.URL.Path, route.PathPrefix)
			if req.URL.Path == "" {
				req.URL.Path = "/"
			}
		}

		// Security: Remove existing X-Forwarded-* headers to prevent spoofing
		// Clients could send malicious headers that backends might trust
		req.Header.Del("X-Forwarded-For")
		req.Header.Del("X-Forwarded-Host")
		req.Header.Del("X-Forwarded-Proto")
		req.Header.Del("X-Real-IP")

		// Set X-Forwarded-* headers with trusted values
		req.Header.Set("X-Forwarded-Host", r.Host)
		req.Header.Set("X-Forwarded-Proto", "https")
		if r.RemoteAddr != "" {
			if idx := strings.LastIndex(r.RemoteAddr, ":"); idx != -1 {
				req.Header.Set("X-Forwarded-For", r.RemoteAddr[:idx])
			}
		}
		req.Header.Set("X-Real-IP", req.Header.Get("X-Forwarded-For"))
	}

	// Error handler
	proxy.ErrorHandler = func(w http.ResponseWriter, r *http.Request, err error) {
		slog.Error("proxy error",
			"hostname", hostname,
			"path", r.URL.Path,
			"target", targetURL.String(),
			"error", err)
		http.Error(w, "Bad Gateway", http.StatusBadGateway)
	}

	// Log the request
	proxy.ModifyResponse = func(resp *http.Response) error {
		duration := time.Since(startTime)
		slog.Info("request",
			"method", r.Method,
			"host", hostname,
			"path", r.URL.Path,
			"status", resp.StatusCode,
			"duration", duration.Round(time.Millisecond),
			"target", route.Backend.ServiceName)

		// Add to log buffer
		h.logBuffer.Add(RequestLog{
			Timestamp: startTime,
			Method:    r.Method,
			Host:      hostname,
			Path:      r.URL.Path,
			Status:    resp.StatusCode,
			Duration:  duration.Milliseconds(),
			Service:   route.Backend.ServiceName,
		})
		return nil
	}

	proxy.ServeHTTP(w, r)
}

func (h *Handler) serveDashboard(w http.ResponseWriter, r *http.Request) {
	routes := h.router.ListRoutes()
	if routes == nil {
		routes = []RouteInfo{}
	}

	// Marshal routes to JSON for Petite Vue initialization
	routesJSON, err := json.Marshal(routes)
	if err != nil {
		slog.Error("failed to marshal routes for dashboard", "error", err)
		routesJSON = []byte("[]")
	}

	data := struct {
		Routes     []RouteInfo
		RoutesJSON template.JS // Safe for embedding in script
		Version    string
	}{
		Routes:     routes,
		RoutesJSON: template.JS(routesJSON),
		Version:    h.statusConfig.Version,
	}

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if err := templates.ExecuteTemplate(w, "dashboard.html", data); err != nil {
		slog.Error("failed to render dashboard template", "error", err)
		http.Error(w, "Internal Server Error", http.StatusInternalServerError)
	}
}

func (h *Handler) serveSSE(w http.ResponseWriter, r *http.Request) {
	// Check for SSE support
	flusher, ok := w.(http.Flusher)
	if !ok {
		http.Error(w, "SSE not supported", http.StatusInternalServerError)
		return
	}

	// Set SSE headers
	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Connection", "keep-alive")

	// Subscribe to route changes
	eventCh, cleanup := h.router.Subscribe(r.Context())
	defer cleanup()

	// Send initial routes immediately
	routes := h.router.ListRoutes()
	h.sendSSEEvent(w, flusher, "routes", routes)

	slog.Debug("SSE client connected", "remote", r.RemoteAddr)

	// Stream events until client disconnects
	for {
		select {
		case <-r.Context().Done():
			slog.Debug("SSE client disconnected", "remote", r.RemoteAddr)
			return

		case event, ok := <-eventCh:
			if !ok {
				return
			}
			h.sendSSEEvent(w, flusher, event.Type, event.Routes)
		}
	}
}

func (h *Handler) sendSSEEvent(w http.ResponseWriter, flusher http.Flusher, eventType string, routes []RouteInfo) {
	data, err := json.Marshal(routes)
	if err != nil {
		slog.Error("failed to marshal SSE event", "error", err)
		return
	}

	// SSE format: event: <type>\ndata: <json>\n\n
	fmt.Fprintf(w, "event: %s\n", eventType)
	fmt.Fprintf(w, "data: %s\n\n", data)
	flusher.Flush()
}

func (h *Handler) serveAsset(w http.ResponseWriter, r *http.Request) {
	// Extract filename from path (e.g., "/_assets/petite-vue.min.js" -> "petite-vue.min.js")
	filename := strings.TrimPrefix(r.URL.Path, "/_assets/")

	// Security: prevent path traversal
	if strings.Contains(filename, "..") || strings.Contains(filename, "/") {
		http.NotFound(w, r)
		return
	}

	// Read from embedded FS
	content, err := templateFS.ReadFile("templates/" + filename)
	if err != nil {
		http.NotFound(w, r)
		return
	}

	// Set content type based on extension
	if strings.HasSuffix(filename, ".js") {
		w.Header().Set("Content-Type", "application/javascript")
	} else if strings.HasSuffix(filename, ".css") {
		w.Header().Set("Content-Type", "text/css")
	} else if strings.HasSuffix(filename, ".svg") {
		w.Header().Set("Content-Type", "image/svg+xml")
	}

	// Cache for 1 hour (static asset)
	w.Header().Set("Cache-Control", "public, max-age=3600")

	w.Write(content)
}

func (h *Handler) serveRoutesAPI(w http.ResponseWriter, r *http.Request) {
	routes := h.router.ListRoutes()

	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(routes); err != nil {
		slog.Error("failed to encode routes as JSON", "error", err)
		http.Error(w, "Internal Server Error", http.StatusInternalServerError)
	}
}

func (h *Handler) serveProjectsAPI(w http.ResponseWriter, r *http.Request) {
	if h.projectStore == nil {
		w.Header().Set("Content-Type", "application/json")
		w.Write([]byte(`{"active":[],"inactive":[]}`))
		return
	}

	type ProjectResponse struct {
		Active   []*project.Project `json:"active"`
		Inactive []*project.Project `json:"inactive"`
	}

	resp := ProjectResponse{
		Active:   h.projectStore.ListActive(),
		Inactive: h.projectStore.ListInactive(),
	}

	// Ensure non-nil slices for JSON
	if resp.Active == nil {
		resp.Active = []*project.Project{}
	}
	if resp.Inactive == nil {
		resp.Inactive = []*project.Project{}
	}

	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(resp); err != nil {
		slog.Error("failed to encode projects as JSON", "error", err)
		http.Error(w, "Internal Server Error", http.StatusInternalServerError)
	}
}

func (h *Handler) serveContainerRestart(w http.ResponseWriter, r *http.Request) {
	// Only allow POST method
	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	// Extract container ID from path: /_api/containers/{id}/restart
	path := strings.TrimPrefix(r.URL.Path, "/_api/containers/")
	path = strings.TrimSuffix(path, "/restart")
	containerID := path

	if containerID == "" {
		http.Error(w, "Container ID is required", http.StatusBadRequest)
		return
	}

	// Check if docker client is available
	if h.dockerClient == nil {
		http.Error(w, "Docker client not available", http.StatusServiceUnavailable)
		return
	}

	// Restart the container
	ctx, cancel := context.WithTimeout(r.Context(), 30*time.Second)
	defer cancel()

	if err := h.dockerClient.RestartContainer(ctx, containerID); err != nil {
		slog.Error("failed to restart container",
			"container", containerID,
			"error", err)
		http.Error(w, fmt.Sprintf("Failed to restart container: %v", err), http.StatusInternalServerError)
		return
	}

	slog.Info("container restarted", "container", containerID)

	// Return success response
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{
		"status":    "restarted",
		"container": containerID,
	})
}

func (h *Handler) serveLogsAPI(w http.ResponseWriter, r *http.Request) {
	logs := h.logBuffer.ListRecent(100)

	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(logs); err != nil {
		slog.Error("failed to encode logs as JSON", "error", err)
		http.Error(w, "Internal Server Error", http.StatusInternalServerError)
	}
}

func (h *Handler) serveLogsSSE(w http.ResponseWriter, r *http.Request) {
	// Check for SSE support
	flusher, ok := w.(http.Flusher)
	if !ok {
		http.Error(w, "SSE not supported", http.StatusInternalServerError)
		return
	}

	// Set SSE headers
	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Connection", "keep-alive")

	// Subscribe to log updates
	logCh, cleanup := h.logBuffer.Subscribe()
	defer cleanup()

	// Send initial logs
	logs := h.logBuffer.ListRecent(50) // Send last 50 on connect
	for i := len(logs) - 1; i >= 0; i-- {
		h.sendLogSSEEvent(w, flusher, logs[i])
	}

	slog.Debug("Logs SSE client connected", "remote", r.RemoteAddr)

	// Stream logs until client disconnects
	for {
		select {
		case <-r.Context().Done():
			slog.Debug("Logs SSE client disconnected", "remote", r.RemoteAddr)
			return

		case log, ok := <-logCh:
			if !ok {
				return
			}
			h.sendLogSSEEvent(w, flusher, log)
		}
	}
}

func (h *Handler) sendLogSSEEvent(w http.ResponseWriter, flusher http.Flusher, log RequestLog) {
	data, err := json.Marshal(log)
	if err != nil {
		slog.Error("failed to marshal log SSE event", "error", err)
		return
	}

	// SSE format: event: log\ndata: <json>\n\n
	fmt.Fprintf(w, "event: log\n")
	fmt.Fprintf(w, "data: %s\n\n", data)
	flusher.Flush()
}

func (h *Handler) serveHealth(w http.ResponseWriter, r *http.Request) {
	routes := h.router.ListRoutes()

	health := struct {
		Status string `json:"status"`
		Routes int    `json:"routes"`
	}{
		Status: "healthy",
		Routes: len(routes),
	}

	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(health); err != nil {
		slog.Error("failed to encode health response", "error", err)
		http.Error(w, "Internal Server Error", http.StatusInternalServerError)
		return
	}
}

func (h *Handler) serveStatus(w http.ResponseWriter, r *http.Request) {
	routes := h.router.ListRoutes()

	// Build status response
	status := &StatusResponse{
		Build: BuildInfo{
			Version: h.statusConfig.Version,
			Commit:  h.statusConfig.Commit,
			Date:    h.statusConfig.Date,
			BuiltBy: h.statusConfig.BuiltBy,
		},
		UptimeSeconds: int64(time.Since(h.statusConfig.StartTime).Seconds()),
		Certificates:  getCertificateStatus(h.statusConfig.CertsDir, h.statusConfig.AutoGenerated),
		Docker: DockerStatus{
			Connected: true, // If we're running, Docker is connected
			Networks:  h.statusConfig.Networks,
		},
		Proxy: ProxyStatus{
			RoutesCount:    len(routes),
			DashboardHost:  h.dashboardHost,
			BaseDomain:     h.statusConfig.BaseDomain,
			HTTPPort:       h.statusConfig.HTTPPort,
			HTTPSPort:      h.statusConfig.HTTPSPort,
			SSESubscribers: h.router.SubscriberCount(),
		},
	}

	// Determine overall health
	status.Health = determineHealth(status)

	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(status); err != nil {
		slog.Error("failed to encode status response", "error", err)
		http.Error(w, "Internal Server Error", http.StatusInternalServerError)
		return
	}
}

func (h *Handler) handleNotFound(w http.ResponseWriter, r *http.Request, hostname string) {
	slog.Warn("no route found",
		"hostname", hostname,
		"path", r.URL.Path)

	routes := h.router.ListRoutes()

	data := struct {
		Hostname      string
		Routes        []RouteInfo
		DashboardHost string
	}{
		Hostname:      hostname,
		Routes:        routes,
		DashboardHost: h.dashboardHost,
	}

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.WriteHeader(http.StatusNotFound)
	if err := templates.ExecuteTemplate(w, "notfound.html", data); err != nil {
		slog.Error("failed to render notfound template", "error", err)
		http.Error(w, "Internal Server Error", http.StatusInternalServerError)
	}
}

func (h *Handler) handleRouteWarning(w http.ResponseWriter, r *http.Request, hostname string, route *Route) {
	slog.Warn("route has warning",
		"hostname", hostname,
		"path", r.URL.Path,
		"warning", route.Backend.Warning,
		"container", route.Backend.ContainerName)

	// Determine warning type for template
	warningType := "unknown"
	if strings.Contains(route.Backend.Warning, "no port") {
		warningType = "no_port"
	} else if strings.Contains(route.Backend.Warning, "hostname conflict") {
		warningType = "conflict"
	}

	data := struct {
		Hostname      string
		ServiceName   string
		Warning       string
		WarningType   string
		DashboardHost string
	}{
		Hostname:      hostname,
		ServiceName:   route.Backend.ServiceName,
		Warning:       route.Backend.Warning,
		WarningType:   warningType,
		DashboardHost: h.dashboardHost,
	}

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.WriteHeader(http.StatusBadGateway)
	if err := templates.ExecuteTemplate(w, "warning.html", data); err != nil {
		slog.Error("failed to render warning template", "error", err)
		http.Error(w, fmt.Sprintf("Service unavailable: %s", route.Backend.Warning), http.StatusBadGateway)
	}
}

// findMockRoute looks for a mock route that matches the request method and path
func (h *Handler) findMockRoute(route *Route, method, path string) *config.MockRoute {
	if len(route.Backend.MockRoutes) == 0 {
		return nil
	}

	// Strip path prefix if configured
	checkPath := path
	if route.PathPrefix != "" {
		checkPath = strings.TrimPrefix(path, route.PathPrefix)
		if checkPath == "" {
			checkPath = "/"
		}
	}

	for _, mock := range route.Backend.MockRoutes {
		if mock.Method == method && mock.Path == checkPath {
			return mock
		}
	}
	return nil
}

// serveMockResponse returns a mock response for the request
func (h *Handler) serveMockResponse(w http.ResponseWriter, r *http.Request, mock *config.MockRoute, hostname string, route *Route) {
	startTime := time.Now()

	// Determine content type based on response body
	contentType := "text/plain"
	body := mock.Body
	if len(body) > 0 {
		// Check if body looks like JSON
		trimmed := strings.TrimSpace(body)
		if (strings.HasPrefix(trimmed, "{") && strings.HasSuffix(trimmed, "}")) ||
			(strings.HasPrefix(trimmed, "[") && strings.HasSuffix(trimmed, "]")) {
			contentType = "application/json"
		}
	}

	w.Header().Set("Content-Type", contentType)
	w.Header().Set("X-Roji-Mock", "true")
	w.WriteHeader(mock.StatusCode)
	w.Write([]byte(body))

	// Log the mock response
	duration := time.Since(startTime)
	slog.Info("mock response",
		"method", r.Method,
		"host", hostname,
		"path", r.URL.Path,
		"status", mock.StatusCode,
		"duration", duration.Round(time.Millisecond),
		"service", route.Backend.ServiceName)

	// Add to log buffer
	h.logBuffer.Add(RequestLog{
		Timestamp: startTime,
		Method:    r.Method,
		Host:      hostname,
		Path:      r.URL.Path,
		Status:    mock.StatusCode,
		Duration:  duration.Milliseconds(),
		Service:   route.Backend.ServiceName,
		IsMock:    true,
	})
}

// RedirectHandler redirects HTTP to HTTPS
type RedirectHandler struct {
	HTTPSPort int
}

// ServeHTTP implements http.Handler for HTTP->HTTPS redirect
func (h *RedirectHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	host := r.Host
	if idx := strings.LastIndex(host, ":"); idx != -1 {
		host = host[:idx]
	}

	targetURL := fmt.Sprintf("https://%s", host)
	if h.HTTPSPort != 443 {
		targetURL = fmt.Sprintf("https://%s:%d", host, h.HTTPSPort)
	}
	targetURL += r.URL.RequestURI()

	http.Redirect(w, r, targetURL, http.StatusMovedPermanently)
}

// serveWebSocket handles WebSocket upgrade requests by proxying to backend
func (h *Handler) serveWebSocket(w http.ResponseWriter, r *http.Request, targetURL *url.URL, route *Route, hostname string, startTime time.Time) {
	// Build WebSocket URL for backend
	wsScheme := "ws"
	backendURL := &url.URL{
		Scheme:   wsScheme,
		Host:     targetURL.Host,
		Path:     r.URL.Path,
		RawQuery: r.URL.RawQuery,
	}

	// Strip path prefix if configured
	if route.PathPrefix != "" {
		backendURL.Path = strings.TrimPrefix(backendURL.Path, route.PathPrefix)
		if backendURL.Path == "" {
			backendURL.Path = "/"
		}
	}

	// Prepare headers for backend connection
	requestHeader := http.Header{}
	// Forward relevant headers
	if origin := r.Header.Get("Origin"); origin != "" {
		requestHeader.Set("Origin", origin)
	}
	// Forward subprotocols if present
	if protocols := r.Header.Get("Sec-WebSocket-Protocol"); protocols != "" {
		requestHeader.Set("Sec-WebSocket-Protocol", protocols)
	}
	// Set X-Forwarded headers
	requestHeader.Set("X-Forwarded-Host", r.Host)
	requestHeader.Set("X-Forwarded-Proto", "https")
	if r.RemoteAddr != "" {
		if idx := strings.LastIndex(r.RemoteAddr, ":"); idx != -1 {
			requestHeader.Set("X-Forwarded-For", r.RemoteAddr[:idx])
		}
	}

	// Connect to backend WebSocket
	slog.Debug("websocket connecting to backend", "url", backendURL.String())
	backendConn, resp, err := websocket.DefaultDialer.Dial(backendURL.String(), requestHeader)
	if err != nil {
		slog.Error("websocket backend connection failed",
			"hostname", hostname,
			"path", r.URL.Path,
			"target", backendURL.String(),
			"error", err)
		if resp != nil {
			http.Error(w, fmt.Sprintf("WebSocket backend error: %s", resp.Status), resp.StatusCode)
		} else {
			http.Error(w, "WebSocket backend connection failed", http.StatusBadGateway)
		}
		return
	}
	defer backendConn.Close()

	// Get response headers from backend for client upgrade
	responseHeader := http.Header{}
	if protocols := resp.Header.Get("Sec-WebSocket-Protocol"); protocols != "" {
		responseHeader.Set("Sec-WebSocket-Protocol", protocols)
	}

	// Upgrade client connection to WebSocket
	clientConn, err := wsUpgrader.Upgrade(w, r, responseHeader)
	if err != nil {
		slog.Error("websocket client upgrade failed",
			"hostname", hostname,
			"path", r.URL.Path,
			"error", err)
		return
	}
	defer clientConn.Close()

	slog.Info("websocket connected",
		"host", hostname,
		"path", r.URL.Path,
		"target", route.Backend.ServiceName)

	// Log the WebSocket connection
	h.logBuffer.Add(RequestLog{
		Timestamp: startTime,
		Method:    "WS",
		Host:      hostname,
		Path:      r.URL.Path,
		Status:    101, // Switching Protocols
		Duration:  time.Since(startTime).Milliseconds(),
		Service:   route.Backend.ServiceName,
	})

	// Create channels to signal completion
	done := make(chan struct{})

	// Proxy messages: client -> backend
	go func() {
		defer close(done)
		for {
			messageType, message, err := clientConn.ReadMessage()
			if err != nil {
				if websocket.IsUnexpectedCloseError(err, websocket.CloseGoingAway, websocket.CloseAbnormalClosure, websocket.CloseNormalClosure) {
					slog.Debug("websocket client read error", "error", err)
				}
				return
			}
			slog.Debug("websocket proxy: client -> backend", "type", messageType, "len", len(message))
			if err := backendConn.WriteMessage(messageType, message); err != nil {
				slog.Debug("websocket backend write error", "error", err)
				return
			}
		}
	}()

	// Proxy messages: backend -> client
	go func() {
		slog.Debug("websocket backend reader goroutine started")
		for {
			messageType, message, err := backendConn.ReadMessage()
			if err != nil {
				slog.Debug("websocket backend read error", "error", err)
				clientConn.WriteMessage(websocket.CloseMessage,
					websocket.FormatCloseMessage(websocket.CloseNormalClosure, ""))
				return
			}
			slog.Debug("websocket proxy: backend -> client", "type", messageType, "len", len(message))
			if err := clientConn.WriteMessage(messageType, message); err != nil {
				slog.Debug("websocket client write error", "error", err)
				return
			}
		}
	}()

	// Wait for either direction to close
	<-done

	slog.Info("websocket disconnected",
		"host", hostname,
		"path", r.URL.Path,
		"duration", time.Since(startTime).Round(time.Millisecond),
		"target", route.Backend.ServiceName)
}

// serveGRPC handles gRPC requests by proxying to backend using HTTP/2
func (h *Handler) serveGRPC(w http.ResponseWriter, r *http.Request, targetURL *url.URL, route *Route, hostname string, startTime time.Time) {
	slog.Debug("grpc request",
		"host", hostname,
		"path", r.URL.Path,
		"content-type", r.Header.Get("Content-Type"))

	// Create reverse proxy with HTTP/2 transport
	proxy := &httputil.ReverseProxy{
		Transport:     http2Transport,
		FlushInterval: -1, // Flush immediately for streaming
		Director: func(req *http.Request) {
			req.URL.Scheme = "http"
			req.URL.Host = targetURL.Host

			// Strip path prefix if configured
			if route.PathPrefix != "" {
				req.URL.Path = strings.TrimPrefix(req.URL.Path, route.PathPrefix)
				if req.URL.Path == "" {
					req.URL.Path = "/"
				}
			}

			// Preserve the original path for gRPC service routing
			if req.URL.RawPath == "" {
				req.URL.RawPath = req.URL.Path
			}

			// Set host header
			req.Host = targetURL.Host

			// Security: Remove existing X-Forwarded-* headers to prevent spoofing
			req.Header.Del("X-Forwarded-For")
			req.Header.Del("X-Forwarded-Host")
			req.Header.Del("X-Forwarded-Proto")
			req.Header.Del("X-Real-IP")

			// Set X-Forwarded-* headers with trusted values
			req.Header.Set("X-Forwarded-Host", r.Host)
			req.Header.Set("X-Forwarded-Proto", "https")
			if r.RemoteAddr != "" {
				if idx := strings.LastIndex(r.RemoteAddr, ":"); idx != -1 {
					req.Header.Set("X-Forwarded-For", r.RemoteAddr[:idx])
				}
			}
		},
		ErrorHandler: func(w http.ResponseWriter, r *http.Request, err error) {
			slog.Error("grpc proxy error",
				"hostname", hostname,
				"path", r.URL.Path,
				"target", targetURL.String(),
				"error", err)
			// Return gRPC-compatible error
			w.Header().Set("Content-Type", "application/grpc")
			w.Header().Set("Grpc-Status", "14") // UNAVAILABLE
			w.Header().Set("Grpc-Message", "backend unavailable")
			w.WriteHeader(http.StatusBadGateway)
		},
		ModifyResponse: func(resp *http.Response) error {
			duration := time.Since(startTime)
			grpcStatus := resp.Header.Get("Grpc-Status")
			if grpcStatus == "" {
				grpcStatus = "0" // OK
			}
			slog.Info("grpc request",
				"method", r.Method,
				"host", hostname,
				"path", r.URL.Path,
				"grpc-status", grpcStatus,
				"duration", duration.Round(time.Millisecond),
				"target", route.Backend.ServiceName)

			// Add to log buffer
			h.logBuffer.Add(RequestLog{
				Timestamp: startTime,
				Method:    "gRPC",
				Host:      hostname,
				Path:      r.URL.Path,
				Status:    resp.StatusCode,
				Duration:  duration.Milliseconds(),
				Service:   route.Backend.ServiceName,
			})
			return nil
		},
	}

	proxy.ServeHTTP(w, r)
}
